### ISSUE TITLE
symfony4 bundle configuration

### ISSUE THREAD

**Issue by rgutknec** [knpuniversity/oauth2-client-bundle#100]
there is no app/config/config.yml anymore in v4. where should I configure this bundle part in v4? (sorry it's probably idiot...), thanks

**Comment by weaverryan** [comment]
Yea, we need to update the docs. Create a config/packages/knpu_lorem_ipsum.yaml file :)

**Comment by rgutknec** [comment]
works fine now. thanks for your help.

**Comment by rgutknec** [comment]
i'm very happy, great job ! :)
