### ISSUE TITLE
Error creating the tutorial's Authenticator class

### ISSUE THREAD

**Issue by dmontero** [knpuniversity/oauth2-client-bundle#108]
Im getting this error:

` Error: Class App\Security\FacebookAuthenticator contains 3 abstract methods
   and must therefore be declared abstract or implement the remaining methods
   (Symfony\Component\Security\Guard\AuthenticatorInterface::onAuthentication
  Failure, Symfony\Component\Security\Guard\AuthenticatorInterface::onAuthent
  icationSuccess, Symfony\Component\Security\Http\EntryPoint\AuthenticationEn
  tryPointInterface::start)`

**Comment by weaverryan** [comment]
Hmm, indeed. I think our example in the README is incomplete - these methods aren't implemented by the base `SocialAuthenticator`, and so you (the user) needs to implement them. We need to update the README!

Thanks for the report!
