### ISSUE TITLE
Call to a member function getMessage() on null

### ISSUE THREAD

**Issue by tristanbes** [knpuniversity/oauth2-client-bundle#115]
Hello,

Running this `knpuniversity/oauth2-client-bundle` on production gives sometimes error like the following: 

![bug](https://user-images.githubusercontent.com/346010/44454438-d8f35480-a5fb-11e8-8b5a-668d30418cf3.png)

```
Error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: 
Call to a member function getMessage() on null in
 <zap>/vendor/knpuniversity/oauth2-client-bundle/src/Security/Exception/IdentityProviderAuthenticationException.php:34
```

I am on version `1.18.0`

Am I doing something wrong ? Or could it be possible that `IdentityProviderAuthenticationException` sometimes has no `getPrevious()` object returned ? (in which case we need the code to be more defensive)

**Comment by weaverryan** [comment]
Wow! That should not be possible! The 3rd argument passed to `parent::__construct()` is that previous exception... and I don't believe the previous exception can ever later be unset in some way. But, there is also an easy work around... so we might as well try it.

Can you look at #118?

**Comment by tristanbes** [comment]
I guess that should do it :-)
