### ISSUE TITLE
Introduce (optional) provider-specific client classes

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/oauth2-client-bundle#13]
Currently, all providers return an instance of `OAuth2Client`, which gives you some nice Symfony-specific sugar. But, if we allow providers to sub-class this (e.g. `FacebookClient`), there are a few advantages:

1) Autowiring: if you use autowiring, then it'll continue to work out-of-the-box even if you have multiple client services
2) Provider-specific users: `FacebookClient` could override `fetchUser()` and `fetchUserFromToken()` *just* to add PHPDoc that describes that you'll get back a specific `FacebookUser`. That's quite helpful for auto-complete
3) (Possibly), if there is some crazy provider-specific functionality, that could be put into the client

**Comment by weaverryan** [comment]
Done!

**Comment by okwinza** [comment]
So basically this is just a wrapper around ResourceOwner class?
:+1:

**Comment by weaverryan** [comment]
It's really a sub-class of `OAuth2Client` - but exactly *because* most libraries have their own ResourceOwner, so I wanted you to get autocomplete when you call getUser() :) - https://github.com/knpuniversity/oauth2-client-bundle/blob/master/Client/Provider/FacebookClient.php#L13

It's a pretty silly small thing - not something I'd do in a project... but if we can put a little more effort in here and make many devs lives easier, then I say we do it!
