### ISSUE TITLE
Run `composer require ` in order to use the "generic" OAuth provider.

### ISSUE THREAD

**Issue by mdimitris** [knpuniversity/oauth2-client-bundle#140]
Hello, I am new to oauth2 services and I have the following issue:
I want to use the generic type but I receive the following error:
Run `composer require ` in order to use the "generic" OAuth provider. I run the command but it asks me for a package name. How can I solve this?

Thanks in advance,
![2018-11-14_1243](https://user-images.githubusercontent.com/13381153/48482493-7d5eee80-e819-11e8-95b3-6f741e2e5f17.png)

**Comment by brianfreytag** [comment]
Per the documentation, to use the generic provider, you first need to go to:

**Comment by mdimitris** [comment]
Thanks for your fast reply. I have to use it because there no provider for the one that I need. I created the provider but I m not sure how I have to declare the class in the yaml file in the provider_class property

**Comment by mdimitris** [comment]
possible duplicate of https://github.com/knpuniversity/oauth2-client-bundle/issues/138
