### ISSUE TITLE
league/oauth2-client package upgraded to 2.4.0 leading to FatalErrorException in LinkedIn.php line 11

### ISSUE THREAD

**Issue by picks44** [knpuniversity/oauth2-client-bundle#143]
Since the upgrade of the `league/oauth2-client` package to 2.4.0, we have this fatal error

`Compile Error: Declaration of League\OAuth2\Client\Provider\LinkedIn::getResourceOwnerDetailsUrl() must be compatible with League\OAuth2\Client\Provider\AbstractProvider::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessTokenInterface $token)
`
Please advise/fix!

**Comment by kumulo** [comment]
You can see a league/oauth2-client open issue here [here](https://github.com/thephpleague/oauth2-client/issues/752)

**Comment by picks44** [comment]
Thanks @kumulo. I rolled back to the previous version in the meantime until a fix is found at `league/oauth2-client`

**Comment by ramsey** [comment]
Please check release 2.4.1 of `league/oauth2-client` and confirm that it fixes this issue. Thanks!

**Comment by picks44** [comment]
@ramsey fixed, thanks!
