### ISSUE TITLE
Generic type and Warning: Class App\Entity\User has no unserializer

### ISSUE THREAD

**Issue by Valantir007** [knpuniversity/oauth2-client-bundle#148]
Hi,
First of all I want to say, you do very good work :)
But... I have one problem :)
I use generic type client and wenn I go to my own oauth server and go back I get exception:
"Warning: Class App\Entity\User has no unserializer"
And I don't know why...
Do you met with something like this?

**Comment by weaverryan** [comment]
Hey @Valantir007!

Hmm, I'm not sure about that. Can you post a stack trace of when this happens? Do you have a custom `serialize()` or `unserialize()` method on your User class or anything like that?

Cheers!

**Comment by Valantir007** [comment]
Hi @weaverryan 
Thank you for your reply. Yeah, sure. Stack trace is below

![image](https://user-images.githubusercontent.com/3719513/49745411-2f65cb00-fc9f-11e8-9619-87d2577c5ffc.png)
And yes, I have serialize and unserialize methods in my App/Entity/User class.
