### ISSUE TITLE
Example on how to use FinishRegistrationBehavior

### ISSUE THREAD

**Issue by IljaN** [knpuniversity/oauth2-client-bundle#152]
https://github.com/knpuniversity/oauth2-client-bundle/blob/master/src/Security/Helper/FinishRegistrationBehavior.php

**Comment by weaverryan** [comment]
Hi there!

This trait is used automatically if you use the SocialAuthenticator - https://github.com/knpuniversity/oauth2-client-bundle/blob/71642a344617bf227aabdb64d7554e36b79d8a1b/src/Security/Authenticator/SocialAuthenticator.php - and this class is documented.

Let me know if you have more questions.

Cheers!

**Comment by IljaN** [comment]
Hi, 

thanks for the quick response.
>This trait is used automatically if you use the SocialAuthenticator

What I miss is rather a usage/best-practice example. From what I gathered I need to check instanceof FinishRegistrationException in onAuthenticationFailure and redirect to a "finish registration" form where the user can enter additional required data.

Not clear to me is how to restart the check-flow after the additional info has been added by the user? Redirect with original code/state back to the initial check route? Or start via method call?

My use-case: Account with same e-mail already exists thus the user can provide the password of the existing account to link both.

Cheerz!

**Comment by weaverryan** [comment]
Ah, let me see if I can clarify - I think you mostly already understand the flow. After redirecting, it sounds like you basically would send them to some login form. On submit, you would create (or re-use) an authenticator that would check the password (like a normal authenticator) and log them in. But, by using the data saved in the session, you could also “link” / update the User object in any way you want to in getUser() before returning it.

Let me know if that makes sense! The issues is that there are many variants to how people want this to work. This bundle allows you to do anything, but I agree that it’s not necessarily obvious. 

If an update to the docs would have helped you, I’d warmly appreciate a PR :).

Cheers!
