### ISSUE TITLE
Deprecation Warning on Symfony 4.2

### ISSUE THREAD

**Issue by michketz** [knpuniversity/oauth2-client-bundle#154]
There is a deprecation warning for the TreeBuilder in Symfony 4.2:

`A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.`

For https://github.com/knpuniversity/oauth2-client-bundle/blob/master/src/DependencyInjection/Configuration.php#L20

**Comment by sadikoff** [comment]
Hi @michketz 
Good catch! It will be fixed via #151 

Cheers!

**Comment by michketz** [comment]
Amazing. 
Didn't found the PR on my search, so this is actually a duplicate. Sorry for that.

Thanks :)
