### ISSUE TITLE
How to implement google one tap sign-in and sign-up with this bundle?

### ISSUE THREAD

**Issue by syeikhanugrah** [knpuniversity/oauth2-client-bundle#158]
https://developers.google.com/identity/one-tap/web/overview

**Comment by syeikhanugrah** [comment]
does it need this bundle?

**Comment by fd6130** [comment]
> does it need this bundle?

Both does the same things. The difference is this bundle use PHP and the other one use JS.

**Comment by weaverryan** [comment]
Hi!

Probably not. The flow with that is this:

A) The user clicks on the JS widget to authenticate
B) After success, your JavaScript is passed a response that contains a token and some user info (I believe).

The job of this bundle is basically (A) and (B) if you want to do a normal, server-side redirect. But in this case, Google is handling it for you. After (B) you could then send the token (via an AJAX request) to your server and use it to authenticate. In that AJAX call, you would make an API request to the Google API to verify its authenticity. This bundle won't help you do that part. Ref: https://developers.google.com/identity/one-tap/android/idtoken-auth

Cheers!
