### ISSUE TITLE
Unit tests fail when additional dependencies are not installed

### ISSUE THREAD

**Issue by outspaced** [knpuniversity/oauth2-client-bundle#16]
**KnpU\OAuth2ClientBundle\Tests\FunctionalTest::testServicesAreUsable** needs to skip services that are not installed.

MyMachine:knpoa alex$ composer require knpuniversity/oauth2-client-bundle
Using version ^0.5.0 for knpuniversity/oauth2-client-bundle
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing guzzlehttp/promises (1.0.3)
    Downloading: 100%         

  - Installing psr/http-message (1.0)
    Downloading: 100%         

  - Installing guzzlehttp/psr7 (1.2.2)
    Downloading: 100%         

  - Installing guzzlehttp/guzzle (6.1.1)
    Downloading: 100%         

  - Installing ircmaxell/security-lib (1.0.0)
    Downloading: 100%         

  - Installing ircmaxell/random-lib (v1.1.0)
    Downloading: 100%         

  - Installing league/oauth2-client (1.2.0)
    Downloading: 100%         

  - Installing symfony/http-foundation (v3.0.2)
    Downloading: 100%         

  - Installing symfony/routing (v3.0.2)
    Downloading: 100%         

  - Installing symfony/dependency-injection (v3.0.2)
    Downloading: 100%         

  - Installing symfony/polyfill-mbstring (v1.1.0)
    Downloading: 100%         

  - Installing symfony/translation (v3.0.2)
    Downloading: 100%         

  - Installing symfony/templating (v3.0.2)
    Downloading: 100%         

  - Installing symfony/stopwatch (v3.0.2)
    Downloading: 100%         

  - Installing symfony/polyfill-util (v1.1.0)
    Downloading: 100%         

  - Installing symfony/polyfill-php56 (v1.1.0)
    Downloading: 100%         

  - Installing symfony/security-core (v3.0.2)
    Downloading: 100%         

  - Installing paragonie/random_compat (1.1.6)
    Loading from cache

  - Installing symfony/polyfill-php70 (v1.1.0)
    Downloading: 100%         

  - Installing symfony/security-csrf (v3.0.2)
    Downloading: 100%         

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/debug (v3.0.2)
    Downloading: 100%         

  - Installing symfony/event-dispatcher (v3.0.2)
    Downloading: 100%         

  - Installing symfony/http-kernel (v3.0.2)
    Downloading: 100%         

  - Installing symfony/finder (v3.0.2)
    Downloading: 100%         

  - Installing symfony/filesystem (v3.0.2)
    Downloading: 100%         

  - Installing symfony/config (v3.0.2)
    Downloading: 100%         

  - Installing symfony/class-loader (v3.0.2)
    Downloading: 100%         

  - Installing symfony/asset (v3.0.2)
    Downloading: 100%         

  - Installing doctrine/cache (v1.6.0)
    Loading from cache

  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/annotations (v1.2.7)
    Downloading: 100%         

  - Installing symfony/framework-bundle (v3.0.2)
    Downloading: 100%         

  - Installing knpuniversity/oauth2-client-bundle (0.5.0)
    Downloading: 100%         

symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/dependency-injection suggests installing symfony/yaml ()
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/translation suggests installing symfony/yaml ()
symfony/security-core suggests installing symfony/validator (For using the user password constraint)
symfony/security-core suggests installing symfony/expression-language (For using the expression voter)
symfony/security-core suggests installing symfony/ldap (For using LDAP integration)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/console ()
symfony/http-kernel suggests installing symfony/var-dumper ()
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
symfony/framework-bundle suggests installing symfony/console (For using the console commands)
symfony/framework-bundle suggests installing symfony/form (For using forms)
symfony/framework-bundle suggests installing symfony/serializer (For using the serializer service)
symfony/framework-bundle suggests installing symfony/validator (For using validation)
symfony/framework-bundle suggests installing symfony/yaml (For using the debug:config and lint:yaml commands)
symfony/framework-bundle suggests installing symfony/property-info (For using the property_info service)
symfony/framework-bundle suggests installing symfony/process (For using the server:run, server:start, server:stop, and server:status commands)
Writing lock file
Generating autoload files

MyMachine:knpoa alex$ phpunit -c vendor/knpuniversity/oauth2-client-bundle/ --bootstrap vendor/autoload.php 
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /private/var/www/tests/knpoa/vendor/knpuniversity/oauth2-client-bundle/phpunit.xml.dist

......................E

Time: 228 ms, Memory: 11.50Mb

There was 1 error:

1) KnpU\OAuth2ClientBundle\Tests\FunctionalTest::testServicesAreUsable
LogicException: Run `composer require league/oauth2-facebook` in order to use the "facebook" OAuth provider.

/private/var/www/tests/knpoa/vendor/knpuniversity/oauth2-client-bundle/DependencyInjection/KnpUOAuth2ClientExtension.php:113
/private/var/www/tests/knpoa/vendor/knpuniversity/oauth2-client-bundle/DependencyInjection/KnpUOAuth2ClientExtension.php:89
/private/var/www/tests/knpoa/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:55
/private/var/www/tests/knpoa/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
/private/var/www/tests/knpoa/vendor/symfony/dependency-injection/Compiler/Compiler.php:107
/private/var/www/tests/knpoa/vendor/symfony/dependency-injection/ContainerBuilder.php:540
/private/var/www/tests/knpoa/vendor/symfony/http-kernel/Kernel.php:477
/private/var/www/tests/knpoa/vendor/symfony/http-kernel/Kernel.php:117
/private/var/www/tests/knpoa/vendor/knpuniversity/oauth2-client-bundle/Tests/FunctionalTest.php:14
                                     
FAILURES!                            
Tests: 23, Assertions: 32, Errors: 1.

**Comment by weaverryan** [comment]
@outspaced thanks for the issue!

The test actually *only* tests the Facebook client - and I have it included as a `dev` dependency. If you moved into the `vendor/knpuniversity/oauth2-client-bundle`, ran `composer install` there and used *its* autoloader, then you would have access to the Facebook library and the tests will pass. I just tested it locally :). This is the better way of running vendor tests: if you use *your* dependencies, that won't include my "dev" dependencies.

Cheers!
