### ISSUE TITLE
Will Google+ API Shutdown affect this bundle

### ISSUE THREAD

**Issue by Mdz-dev** [knpuniversity/oauth2-client-bundle#161]
Not an issue, just an inquiry,

Google is shutting down the Google+ API on March 7, 2019. Will this bundle be affected by this change? https://developers.google.com/+/api-shutdown

**Comment by weaverryan** [comment]
I have no idea :). It won't affect this bundle, but it may affect the actual library that talks to Google's OAuth. Here's a commit I found on that library: https://github.com/thephpleague/oauth2-google/commit/8ce837dfc8d7411fae1a2d977451b828ce8e1281

Cheers!

**Comment by fdiedler** [comment]
If anyone has the answer to this question, please tell :)

But, we will know the answer on March 7, 2019.

Thanks

**Comment by weaverryan** [comment]
As long as you're using version 3.0 or higher of `thephpleague/oauth2-google`, I think you're fine - as they have removed the old functionality in that version (so there is now way to use that version and get things working by relying on the functionality that will be removed).

**Comment by Mdz-dev** [comment]
I'm not very familiar with Google Sign in API, but I think you guys maybe should change some parameter names. As I see, they are dropping the names `{google-app-id}` and `{google-app-secret}` and using [OpenID Connect][openid-connect].

> This package uses [OpenID Connect][openid-connect] to authenticate users with
Google accounts.

also

> To use this package, it will be necessary to have a Google client ID and client
secret. These are referred to as `{google-client-id}` and `{google-client-secret}`
in the documentation.

Excuse me if i'm mistaken!

**Comment by weaverryan** [comment]
> As I see, they are dropping the names `{google-app-id}` and `{google-app-secret}` and using [OpenID Connect][openid-connect].

Yes, but both ultimately are mapped to the `clientId` and `clientSecret` params passed to the library - https://github.com/thephpleague/oauth2-google/commit/8ce837dfc8d7411fae1a2d977451b828ce8e1281#diff-04c6e90faac2675aa89e2176d2eec7d8R57

Basically, I think that a user of the `thephpleague/oauth2-google` library may need to make some changes to get v 3.0 to work with openid - getting a Google client ID / secret etc. Then you will use these values for the `client_id` and `client_secret` params in this bundle. This bundle doesn't have anything about `google-app-id` or anything similar - you can see all the options here: https://github.com/knpuniversity/oauth2-client-bundle/blob/aa5e8e530b4710d3307d2f9b48f76eb17a8b51e2/src/DependencyInjection/Providers/GoogleProviderConfigurator.php#L43-L67

Cheers!

**Comment by fdiedler** [comment]
I found this link : 
https://github.com/thephpleague/oauth2-google/issues/63

It looks like everything is okay and the bundle has been updated but ot really sure.

Thanks
