### ISSUE TITLE
Update for the new Google Sign-in Oauth ?

### ISSUE THREAD

**Issue by fdiedler** [knpuniversity/oauth2-client-bundle#162]
Hi,

I receive an email from Google entitled "Google+ APIs and OAuth requests are being shutdown on March 7, 2019". I think this bundle use for Google the _Google+ API_ but I am not sure.

Google says that developers should migrate from the Google+ Sign-In feature to the more comprehensive **Google Sign-in** authentication system.

What Google API use this bundle ?

Thanks

**Comment by weaverryan** [comment]
Hi @fdiedler!

See #161 for some information about this.

Cheers!

**Comment by fdiedler** [comment]
Thanks :)
