### ISSUE TITLE
Integrate this bundle with Symfony and frontend app

### ISSUE THREAD

**Issue by jdflament** [knpuniversity/oauth2-client-bundle#165]
Hi,

I'm actually doing a project with Symfony 4 (API) and Angular 7.
I would like to integrate this bundle into my server side, and authenticate with my Angular application to accept user for using my application and talk with my Symfony API.
How can I do this ? Do you have any tutorial or recommandation ?
Am I supposed to use a frontend plugin?

Best Regards,

**Comment by weaverryan** [comment]
Hi @jdflament!

Yea, I'm not sure. I think typically you handle everything client-side (the OAuth flow), then when it's completed, you send the access token only to the Symfony app. The server can then use that to communicate back to the OAuth server, fetch some basic user info, and authenticate the user inside of Symfony. I would probably not use this bundle in that case - as you really don't need to do the OAuth flow in Symfony - you would just need to make some API requests to whatever OAuth server (e.g. Facebook) using the access token that your Angular app sent to your server.

Good luck!
