### ISSUE TITLE
Step3: where to save the code?

### ISSUE THREAD

**Issue by bwakkie** [knpuniversity/oauth2-client-bundle#166]
I am having problems understanding where to place the code in Step 3. I tried to create a file src/Controller/FacebookController.php with the code, but I get an error:

`Expected to find class "App\Controller\FacebookController" in file "/my_project/src/Controller/FacebookController.php" while importing services from resource "../src/*", but it was not found! Check the namespace prefix used with the resource in /my_project/config/services.yaml (which is loaded in resource "/home/bastiaan/development/syrphidae.2/my_project/config/services.yaml").`

PS. I am using the symfony demo as base and try to implement a facebook login.

**Comment by bocharsky-bw** [comment]
Hey @bwakkie ! Could you double check the namespace of your `FacebookController`? So, you should have `src/Controller/FacebookController.php ` exact path to the controller and inside you should have `namespace App\Controller;`. And in your `composer.json` your should have `"App\\": "src/"`. Most probably you have a typo somewhere in the path, filename or namespace. Also, do you have any code in your `services.yaml` related to this?

**Comment by bwakkie** [comment]
The file FacebookController.php contains exactly the same code as in [step 3](https://github.com/knpuniversity/oauth2-client-bundle#step-3-use-the-client-service) So `namespace App\Controller;` is on the first line there.

Within composer.json there is a part with `"App\\": "src/"`.:
```
   "autoload": {
       "psr-4": {
           "App\\": "src/"
```

config/services.yaml:
```
   App\Controller\:
       resource: '../src/Controller'
       tags: ['controller.service_arguments']
```
when I restart the dev server I get now the following error which might help me on my way?:
```
  The autoloader expected class "App\Controller\FacebookController" to be defined in file "/home/my_project/vendor/composer/../../src/Controller/FacebookController.php". The file was found but the class  
   was not in it, the class name or namespace probably has a typo in /my_project/config/services.yaml (which is loaded in resource "/my_project/config/services  
  .yaml"). 
```
Do I need to add something to the services.yaml file perhaps?

**Comment by bocharsky-bw** [comment]
Hm, ok, you have `namespace App\Controller;` that's good, but what is your class name there? Please, double check that it's exactly `class FacebookController`

**Comment by bwakkie** [comment]
Yes the same as far as I can see:
```
$cat src/Controller/FacebookController.php:

namespace App\Controller;

use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class FacebookController extends Controller
{
    /**
     * Link to this controller to start the "connect" process
     *
     * @Route("/connect/facebook", name="connect_facebook_start")
     */
    public function connectAction(ClientRegistry $clientRegistry)
    {
        // on Symfony 3.3 or lower, $clientRegistry = $this->get('knpu.oauth2.registry');
        // will redirect to Facebook!
        return $clientRegistry
            ->getClient('facebook_main') // key used in config/packages/knpu_oauth2_client.yaml
            ->redirect([
                'public_profile', 'email' // the scopes you want to access
            ])
        ;
        }

    /**
     * After going to Facebook, you're redirected back here
     * because this is the "redirect_route" you configured
     * in config/packages/knpu_oauth2_client.yaml
     *
     * @Route("/connect/facebook/check", name="connect_facebook_check")
     */
    public function connectCheckAction(Request $request, ClientRegistry $clientRegistry)
    {
        // ** if you want to *authenticate* the user, then
        // leave this method blank and create a Guard authenticator
        // (read below)

        /** @var \KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient $client */
        $client = $clientRegistry->getClient('facebook_main');

        try {
            // the exact class depends on which provider you're using
            /** @var \League\OAuth2\Client\Provider\FacebookUser $user */
            $user = $client->fetchUser();

            // do something with all this new power!
            // e.g. $name = $user->getFirstName();
            var_dump($user); die;
            // ...
        } catch (IdentityProviderException $e) {
            // something went wrong!
            // probably you should return the reason to the user
            var_dump($e->getMessage()); die;
        }
    }
}
```

**Comment by jrushlow** [comment]
I'm going to close this issue as it is pretty dated. Feel free to re-open if you are still experiencing trouble!
