### ISSUE TITLE
Problems configuring Facebook 

### ISSUE THREAD

**Issue by msechi** [knpuniversity/oauth2-client-bundle#169]
Hello guys

configuring facebook, I am getting this error error (on FB) :
The domain of this URL isn't included in the app's domains. 
I think because I am developing inside a docker container and my local domain is myapp.loc

Then I am redirected to connect/facebook/check without the code query string parameter.

I added myapp.loc in facebook for developers in Settings -> basic -> App Domain with no luck.

anyone can share how to solve this?

thanks

**Comment by msechi** [comment]
ok I find out that I needed to configure my facebook app putting the setting Client OAuth Login  = NO and the url in Facebook Login -> settings -> Valid OAuth Redirect URIs. The controller works and I can fetch data from FB.

Then I made the FacebookAuthenticator, left the connectCheckAction method empty and I am getting this message:
`The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned null. Did you forget to add a return statement somewhere in your controller?`

Same thing if I add a return statement.

any idea?

thanks
M

**Comment by weaverryan** [comment]
That last error can mean that either: (A) your authenticator is not being called at all or, more likely, (B) it’s being called, but either you’re returning false from supports() or not redirecting in onAuthenticationError or onAuthenticationSuccess - because you’re not redirecting, even if auth is successful, the request is then continuing to the controller, which is blank (because we never intended for the request to get there - we want the authenticator to redirect on error or success.

Cheers!

**Comment by akincer** [comment]
You should be able to fix this error by adding this under Valid OAuth Redirect URIs:

yourdomain/connect/facebook/check

**Comment by lahmacun** [comment]
I'm getting the same error, I setted up everything correctly. Actuallt it was working few months ago but now it doesn't. Interesting fact, it's working on localhost but doesn't work on my domain. And another interesting thing is I'm getting German error message from Facebook. I don't have anyhting about German but the error message is in German.

I'm going crazy, I can't solve it for a month.

**Comment by weaverryan** [comment]
Yikes! Yea, this is the hardest part of OAuth - and I particularly find Facebook confusing. All you can do is triple check your configuration and setup in your app. About the German, that might be an indication that something in your Facebook app is configured for German (or was created by a user that prefers German?? Totally guessing?) and not something from your code.

Good luck!
