### ISSUE TITLE
Typo bug in tests ?

### ISSUE THREAD

**Issue by VincentClair** [knpuniversity/oauth2-client-bundle#174]
https://github.com/knpuniversity/oauth2-client-bundle/blob/10f52b23c3be553984fd7378b9a3d0682c47abc8/tests/DependencyInjection/KnpUOAuth2ClientExtensionTest.php#L263

Must be "redirect_**route**" ?

https://github.com/knpuniversity/oauth2-client-bundle/blob/10f52b23c3be553984fd7378b9a3d0682c47abc8/tests/DependencyInjection/KnpUOAuth2ClientExtensionTest.php#L271

Must be "redirect_para**m**s" ?

**Comment by bocharsky-bw** [comment]
Wow, great catch 👍 

Could you open a PR for this?

**Comment by bocharsky-bw** [comment]
Looks like fixed in #176
