### ISSUE TITLE
j4k/oauth2-vkontakte is not supported anymore

### ISSUE THREAD

**Issue by kafkiansky** [knpuniversity/oauth2-client-bundle#177]
Hi everyone, I need to implement oauth via vk, but j4k/oauth2-vkontakte doesn't implement the latest version of oauth2-client-bundle and that's why I can't use it in my project. How can I solve this problem?

**Comment by weaverryan** [comment]
Hey @kafkiansky!

What do you mean by:

> j4k/oauth2-vkontakte doesn't implement the latest version of oauth2-client-bundle

Do you have an install error when you try to install that library and also this bundle? One thing I *did* notice is that library only works with the old version of `league/oauth2-client` (version 1): https://github.com/j4k/oauth2-vkontakte/blob/f11cf7bbc066a49164a5c59eaf50e47f59d641b5/composer.json#L17

So, you will need to specifically install version 1 of `league/oauth2-client`, otherwise the vkontakte won't install correctly. This bundle supports both versions of `league/oauth2-client`

**Comment by kafkiansky** [comment]
@weaverryan, i try to install league/oauth2-client 1 version, but

```knpuniversity/oauth2-client-bundle v1.28.0 requires league/oauth2-client ^1.0|^2.0 -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.4.0, 2.4.1] but these conflict with your requirements or minimum-stability.```

**Comment by weaverryan** [comment]
Can you post the full message? And your `composer.json` file?

**Comment by kafkiansky** [comment]
@weaverryan, composer.json

{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "cocur/slugify": "^3.1",
        "fzaninotto/faker": "^1.8",
        "knpuniversity/oauth2-client-bundle": "^1.28",
        "league/oauth2-github": "^2.0",
        "league/oauth2-google": "^3.0",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "4.2.*",
        "symfony/console": "4.2.*",
        "symfony/dotenv": "4.2.*",
        "symfony/expression-language": "4.2.*",
        "symfony/flex": "^1.1",
        "symfony/form": "4.2.*",
        "symfony/framework-bundle": "4.2.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "4.2.*",
        "symfony/security-bundle": "4.2.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.2.*",
        "symfony/twig-bundle": "4.2.*",
        "symfony/validator": "4.2.*",
        "symfony/web-link": "4.2.*",
        "symfony/webpack-encore-bundle": "^1.1",
        "symfony/yaml": "4.2.*"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.1",
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "4.2.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "kafkiansky\\OAuth2\\Client\\Provider\\": "lib/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.2.*"
        }
    },
    "minimum-stability": "dev"
}

Error:
knpuniversity/oauth2-client-bundle v1.28.0 requires league/oauth2-client ^1.0|^2.0 -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.4.0, 2.4.1] but these conflict with your requirements or minimum-stability.

**Comment by weaverryan** [comment]
It's probably because both `league/oauth2-google` and `oauth2-github` require version *2* of `league/oauth2-client`. So, the real problem is that you can't have version 1 and version 2 of `league/oauth2-client` installed simultaneously. You either won't be able to use the old vkontakte client along with those other two clients, or you'll need to purposely use old versions of those libraries, which is a bummer :/. Basically, because the vkonktakte library is out of date, it's making your job hard :/.

**Comment by tomgif** [comment]
I made my own. https://gist.github.com/tomgif/a13d6809dfcc6b71de8feb4cb01ca88e
Vkontakte - old name. Now it's called - vk
