### ISSUE TITLE
HTTP url generated when behind a HTTPS terminated proxy

### ISSUE THREAD

**Issue by brad-goss** [knpuniversity/oauth2-client-bundle#179]
My site seems to be working as expected when behind a HTTPS terminated proxy. HTTPS urls are generated everywhere on the site, except when the OAuth2-Client-Bundle generates the redirect URL, it generates a HTTP url.

I tried the solutions offered:

1. https://github.com/knpuniversity/oauth2-client-bundle/issues/116
With a Google provider

 Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "provider_options" under "knpu_oauth2_client/clients/google_main". Available options are "access_type", "client_id", "client_secret", "hosted_domain", "redirect_params", "redirect_route", "use_oidc_mode", "use_state", "user_fields". in /var/www/html/vendor/symfony/config/Definition/ArrayNode.php:331 Stack trace: #0 /var/www/html/vendor/symfony/config/Definition/BaseNode.php(363): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) #1 /var/www/html/vendor/symfony/config/Definition/Processor.php(35): Symfony\Component\Config\Definition\BaseNode->normalize(Array) #2 /var/www/html/vendor/knpuniversity/oauth2-client-bundle/src/DependencyInjection/KnpUOAuth2ClientExtension.php(193): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array) #3 /var/www/html/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php( in /var/www/html/vendor/symfony/config/Definition/ArrayNode.php on line 331

2. https://github.com/knpuniversity/oauth2-client-bundle/issues/95
This puts my site into a redirect loop.

Any ideas?

**Comment by brad-goss** [comment]
Well, my proxy isn't setup 100% correctly. I'm not certain how the rest of my site is working properly.

I added to my public/index.php
Request::setTrustedProxies(["172.18.0.15"], Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);

And, this fixed my problem with OAuth2-Client-Bundle.

The default public/index.php tries to automatically detect the IP address, but I am not passing it along from the proxy. So, i need to fix that to make it work properly.

**Comment by weaverryan** [comment]
Thanks for sharing! Yes, being behind a proxy requires this extra setup, and can be hard to debug :)

**Comment by karser** [comment]
You can also set this variable in your `.env` or `.env.local`
```
TRUSTED_PROXIES=127.0.0.0/8,x.x.x.x/8
```
where x.x.x.x is your proxy ip address
