### ISSUE TITLE
Use select_account in prompt option

### ISSUE THREAD

**Issue by julienduthoit** [knpuniversity/oauth2-client-bundle#180]
Hi, 

I try too add the prompt option as shown in [https://developers.google.com/identity/protocols/OAuth2WebServer](url) without success.
I want an account selector displaying everytime I have to login to my app.

Is there a way to add options in knpu_oauth2_client as available for the generic provider?

Thanks

**Comment by weaverryan** [comment]
Hey @julienduthoit!

Hmm, no - that's not possible. It looks like the [GoogleProviderConfigurator](https://github.com/knpuniversity/oauth2-client-bundle/blob/master/src/DependencyInjection/Providers/GoogleProviderConfigurator.php) needs that option added. Could you open a PR?

**Comment by julienduthoit** [comment]
Hi @weaverryan ,
Actually, it's already available in the redirect method of the Oauth Client. :)

`return $clientRegistry
            ->getClient('google')// key used in config/packages/knpu_oauth2_client.yaml
            ->redirect([
                'profile', 'openid', 'address' // the scopes you want to access
            ], ['prompt' => 'select_account']);`

I hope it will be usefull for someone.

Thanks,
