### ISSUE TITLE
Return back to login screen on error

### ISSUE THREAD

**Issue by akincer** [knpuniversity/oauth2-client-bundle#181]
I'm trying to do two different paths for people that want to leverage Facebook:

1. Link a Facebook account to a new registration.
2. Authenticate via Facebook for registered accounts with a linked Facebook account.

I have the first one working, but I'm trying to deal with the case where a user tries to login with a Facebook user that hasn't been linked yet. This returns a bland page with the message of "Username could not be found".

Instead, I'd like to be able to redirect back to the login page with an error message alerting the user that they're trying to login with an unlinked Facebook account. Is there a common way to deal with this that I'm missing?

**Comment by akincer** [comment]
Figured out a workaround in case anyone else wants to redirect back to their login form (or whatever).

Inside of the onAuthenticationFailure method of the FacebookAuthenticator class, issue this command:

`return new RedirectResponse($this->router->generate('my_login_route_name'));`

Notes:


1. You'll need to inject the RouterInterface in the constructor and set a new private property $router to point to it.

2. Make sure you add the RouterInterface and RedirectResponse use statements.

3. Use the SessionInterface if you want to pass the error back to the route for usage in Twig. The fact that an error was thrown seems to be lost on AuthenticationUtils if the route you're calling checks for the latest error to pass to your template.

**Comment by larzuk91** [comment]
Hey @akincer 

Thanks for sharing your solution. I think item 3 makes sense since you are redirecting one more time
