### ISSUE TITLE
Request custom URL on Strava with token & how to uset the refresh token?

### ISSUE THREAD

**Issue by InsulinJunkieDe** [knpuniversity/oauth2-client-bundle#185]
Hi,

thanks to the fantastic guide I could manage to connect to strava, without a hassle. Big thanks for this!!

As I could see in the sample, I can request the athlete information. `$user = $client->getAccessToken();` This gives the user (`GET /athlete`) including access & refresh tokens. But now I'm kind of stuck, since I don't have much of a clue on how to access this url, with the access token included: `GET /athlete/activities`. Can you give me a hint?

With the login I get a new access & refresh token, which I can save and use later again. 
Do I need to manually refresh the token, or is it enough to make a new request with the refresh token?

Background: I want to save the accesstoken for later use and periodically call the page to see if are any activities have been posted.

Many thanks in advance!

**Comment by weaverryan** [comment]
Hey @InsulinJunkieDe!

Sorry for my slow reply. I'm not sure I totally understand, but probably what you will want to do is this:

1) Use `$client->getAccessToken();` to get the access token. Do not use `$client->fetchUser()`, as this is just a shortcut to use the access token to get some user information. For you, it's better probably better to get the access token directly and use it later. I'm not sure how you're getting the refresh token... but nice job :p

2) Once you have the access token, you'll need to install & use some 3rd party HTTP client so you can make HTTP requests (e.g. https://symfony.com/doc/current/components/http_client.html). Then, you'll attach the access token to the `Authorization` header - you'll use your HTTP client to add an `Authorization` header that looks like this `Bearer YOUR TOKEN HERE` - yes, literally the word "Bearer" a space, then your token. You can see how the OAuth library does that internally here: https://github.com/thephpleague/oauth2-client/blob/master/src/Tool/BearerAuthorizationTrait.php - you should be able to then use your access token to talk to any endpoints

3) Ultimately, during authentication, you'll save the "refresh token" (not the access token) somewhere for later use (e.g. the database, attached to the User). The instructions on how to use it are here: https://developers.strava.com/docs/authentication/#refresh-expired-access-tokens - you basically make a request (again, using some 3rd party HTTP client) to get a new access token (by using the refresh token), use that access token, then discard it.

I hope this helps!
