### ISSUE TITLE
Case "remember me" is undocumented

### ISSUE THREAD

**Issue by garak** [knpuniversity/oauth2-client-bundle#187]
Documentation in main README reads as follow (when decribing `MyFacebookAuthenticator`):
```php
public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
{
    // on success, let the request continue
    return null;
}
```
Unfortunately, this is not enough.
If you use `remember_me` option in your firewall, you can't return null: you'll hit following exception:
>App\Security\MyFacebookAuthenticator::onAuthenticationSuccess *must* return a Response if you want to use the remember me functionality. Return a Response, or set remember_me to false under the guard configuration.

The comment in code above should include such case

**Comment by weaverryan** [comment]
You're right - thanks for the report. Actually, redirecting in this situation is much more realistic anyways... not sure why I documented it to like this. I've just changed it to show a redirect by default.

Cheers!
