### ISSUE TITLE
Enhacement: Sign in with Apple

### ISSUE THREAD

**Issue by xeux** [knpuniversity/oauth2-client-bundle#188]
This is more of a question: there is no direct integration with Sign in with Apple, is there a reason? Do you recommend to use Auth0?

**Comment by weaverryan** [comment]
Hi there!

This bundle wraps the https://github.com/thephpleague/oauth2-client library and client libraries for specific OAuth2 sites. I'm not sure if there is one fore Apple or not - I'm also not sure what their OAuth support looks like. If they support OAuth2, and there is no client library yet for them, you can use the "generic" provider to implement it manually.

Cheers!
