### ISSUE TITLE
Add a twitter client

### ISSUE THREAD

**Issue by symac** [knpuniversity/oauth2-client-bundle#189]
More than one year ago, the issue #98 was asking for it but it had been closed because at this time, twitter was only supporting oauth 1. If I understand correctly what I can read at https://developer.twitter.com/en/docs/basics/authentication/overview/oauth : "Twitter uses OAuth 1.0a and OAuth2 to provide authorized access to the API.". 

So I assume it is now possible to build an official twitter client for this library, and it would be great!

**Comment by weaverryan** [comment]
I don't really know for sure, but I believe (sadly) that Twitter *still* doesn't support OAuth2: https://github.com/Maslosoft/oauth2-twitter/issues/1#issuecomment-233590674

**Comment by Zefling** [comment]
Is it still impossible? 
https://developer.twitter.com/en/docs/authentication/oauth-2-0
