### ISSUE TITLE
Issue when configuring keycloak

### ISSUE THREAD

**Issue by tejasgosai88** [knpuniversity/oauth2-client-bundle#190]
I wanted to configure keycloak, after configuration and GuardAuthenticator.
I get following error:

> Authentication failed! Did you authorize our app?
I did a little digging, it comes from OAuth2Client class when there is no "code" in request. I could not find in documentation, what is "code" and how to use it?

**Comment by bocharsky-bw** [comment]
Hey @tejasgosai88 ,

`code` is a query parameter in the URL. When you send a request to Keycloak, it redirects you back to your website and put that code in the URL query parameter. Please, take a look at example for keycloak oauth2 library: https://github.com/stevenmaguire/oauth2-keycloak#authorization-code-flow

I hope this helps!

Cheers!

**Comment by tejasgosai88** [comment]
Sorry to reply so late. We are not going to use keycloak now. But thanks for explanation. I'll try on sample project.
