### ISSUE TITLE
The URI /connect/facebook/check not fetching any $user

### ISSUE THREAD

**Issue by VGzsysadm** [knpuniversity/oauth2-client-bundle#192]
Hi.

Afer configure whole the env, retrieving data from /connect/facebook/check i'm receiving all time {"status":false,"message":"User not found!"}

Using one guard or two, Google oauth2 works without any problem. Following this guide for facebook should work?

Thanks

Kind regards.

This is my controller: https://pastebin.com/zVN1Efzs

**Comment by VGzsysadm** [comment]
Ok sorry, the bundle works good. It was my problem at the guard, i had a typo in the URL

**Comment by bocharsky-bw** [comment]
Hey @VGzsysadm ,

I'm glad you were able to solve the problem yourself! And thanks for sharing the solution!

Cheers!
