### ISSUE TITLE
There is no extension able to load the configuration for "knpu_oauth2_client"

### ISSUE THREAD

**Issue by flesage-000** [knpuniversity/oauth2-client-bundle#195]
Hello,

I'trying to use oauth2-client-bundle for a project but i'm stuck at STEP 3 and got this error :

> There is no extension able to load the configuration for "knpu_oauth2_client"

Here is my script (but similar to HP tutorial)

_FacebookController.php_
`<?php
namespace App\Controller;

use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class FacebookController extends Controller
{
    /**
     * Link to this controller to start the "connect" process
     *
     * @Route("/connect/facebook", name="connect_facebook_start")
     */
    public function connectAction(ClientRegistry $clientRegistry)
    {
        // on Symfony 3.3 or lower, $clientRegistry = $this->get('knpu.oauth2.registry');

        // will redirect to Facebook!
        return $clientRegistry
            ->getClient('facebook_main') // key used in config/packages/knpu_oauth2_client.yaml
            ->redirect([
	    	'identify' // the scopes you want to access
            ])
        ;
	}

    /**
     * After going to Facebook, you're redirected back here
     * because this is the "redirect_route" you configured
     * in config/packages/knpu_oauth2_client.yaml
     *
     * @Route("/connect/facebook/check", name="connect_facebook_check")
     */
    public function connectCheckAction(Request $request, ClientRegistry $clientRegistry)
    {
        // ** if you want to *authenticate* the user, then
        // leave this method blank and create a Guard authenticator
        // (read below)

        /** @var \KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient $client */
        $client = $clientRegistry->getClient('facebook_main');

        try {
            // the exact class depends on which provider you're using
            /** @var \League\OAuth2\Client\Provider\FacebookUser $user */
            $user = $client->fetchUser();

            // do something with all this new power!
	    // e.g. $name = $user->getFirstName();
            var_dump($user); die;
            // ...
        } catch (IdentityProviderException $e) {
            // something went wrong!
            // probably you should return the reason to the user
            var_dump($e->getMessage()); die;
        }
    }
}`

knpu_oauth2_client.yaml
`knpu_oauth2_client:
    clients:
        # will create service: "knpu.oauth2.client.discord"
        # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\DiscordClient
        # composer require wohali/oauth2-discord-new
        discord_main:
            # must be "discord" - it activates that type!
            type: discord
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
            client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_discord_check
            redirect_params: {}

            # whether to check OAuth2 "state": defaults to true
            # use_state: true
      # the key "facebook_main" can be anything, it
      # will create a service: "knpu.oauth2.client.facebook_main"
        facebook_main:
            # this will be one of the supported types
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.12`
_- Initialy i use this to a OAuth2 Discord, so i duplicate for discord during the tutorial, but i have the same error for both_
_- env var are set in .env file_

I'm new to Symfony framework, so i assume that question is probably stupid :D.

**Comment by larzuk91** [comment]
Hey @flesage-000 what the error means
>There is no extension able to load the configuration for "knpu_oauth2_client"

Is that Symfony is reading your `knpu_oauth2_client.yaml` file but nothing could process it. I believe this is happening because the bundle is not activated. Double check your `config/bundles.php` file. You are on Symfony4, right?

**Comment by flesage-000** [comment]
Hey @larzuk91 

Indeed i'm on Symfony 4.

I read something about that but i thought it was automatic for this version of Symfony !

I'll search on the web how to activate manually a bundle, thx !

**Comment by larzuk91** [comment]
>Indeed i'm on Symfony 4.

Hmm, in that case, it should be enabled automatically. Look for the bundle inside `config/bundles.php` If it's not for any reason, then just add it there and try again

**Comment by flesage-000** [comment]
Here is the bundles.php

`<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
];`

**Comment by flesage-000** [comment]
Well... @larzuk91 

Now it's works, it seems that i don't understand an install question

> The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/master/knpuniversity/oauth2-client-bundle/1.20

I thought by say "n" it install another version....

BTW, i can now see the discord login :D. Thanks a lot :)

**Comment by larzuk91** [comment]
Ah, yes, by default composer asks you if you want to install recipes coming from the contrib repository. It's just for security reasons, there could be a bad/hacky recipe.

I'm glad to know that you could fix your problem. I'm closing this issue but if you have more problems feel free to open another onw
