### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by tacman** [knpuniversity/oauth2-client-bundle#214]
composer.json restricts this bundle to Symony 3 and 4.  What's necessary to allow Symfony5 support?

```json
       "symfony/framework-bundle": "^3.4|^4.0",
        "symfony/dependency-injection": "^3.4|^4.0",
        "symfony/routing": "^3.4|^4.0",
        "symfony/http-foundation": "^3.4|^4.0",
```

I've been trying to find a tutorial on how to contribute to a 3rd party bundle, but I keep getting stuck trying to figure out how to update composer so that it uses a local development version of my fork.  Any suggestions?  Better, of course, would be to have Ryan or someone else who knows this well fix it.  Since Symfony 5 in at Release Candidate stage, I think it'd be great to get this working.

**Comment by bocharsky-bw** [comment]
Yeah, we should allow Symfony 5. And I think there's a PR now, see #216 - feel free give a code review on it

**Comment by tacman** [comment]
When testing this locally with the PR, it seems to be working okay for me.  So let's merge it.

**Comment by weaverryan** [comment]
Thanks for testing it Tac - that makes the merge much easier :). I've just merged the PR and tagged a new release. If there are any problems, let us know!

> but I keep getting stuck trying to figure out how to update composer so that it uses a local development version of my fork. Any suggestions? 

What I usually do (and which works in all cases, except for some rare cases) is to:

A) Clone this bundle somewhere on your computer
B) Install the *stable* version of this bundle into a *project* you have somewhere
C) Remove the `vendor/knpuniversity/oauth2-client-bundle` in your *project* and symlink it to wherever your clone of the bundle is.

Cheers!
