### ISSUE TITLE
Facebook oauth fetch user Error : OAuthException: Can't Load URL: The domain of this URL isn't included in the app's domains. 

### ISSUE THREAD

**Issue by chanondb** [knpuniversity/oauth2-client-bundle#217]
Hi , 
I tried to followed , sample on FacebookController in README but always get the error when trying to fetchUser on server side as followed.

> string(8) "get user" string(210) "OAuthException: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings."

```
/**
     * After going to Facebook, you're redirected back here
     * because this is the "redirect_route" you configured
     * in config/packages/knpu_oauth2_client.yaml
     *
     * @Route("/connect/facebook/check", name="connect_facebook_check")
     */
    public function connectCheckAction(Request $request)
    {
        // ** if you want to *authenticate* the user, then
        // leave this method blank and create a Guard authenticator
        // (read below)
        
        /** @var \KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient $client */
        $client = $this->get('knpu.oauth2.registry')->getClient('facebook');
        
        try {
            // the exact class depends on which provider you're using
            var_dump("get user");
            /** @var \League\OAuth2\Client\Provider\FacebookUser $user */
            $facebookUser = $client->fetchUser();
            var_dump("process user");
            // do something with all this new power!
            // e.g. $name = $facebookUser->getFirstName();
            $user = $this->getUserByFacebookUser($facebookUser);
            
            $token = new UsernamePasswordToken($user, null, 'main', $user->getRoles());
            $this->container->get('security.token_storage')->setToken($token);
            $this->container->get('session')->set('_security_main', serialize($token));
            // The user is now logged in, you can redirect or do whatever.
            
            return $this->redirectToRoute('frontend_profile');
            
            // ...
            
        } catch (IdentityProviderException $e) {
            // something went wrong!
            // probably you should return the reason to the user
            
//             $this->logger->error($e->getMessage());
            var_dump($e->getMessage()); 
            die;
            throw $e;
            //return new Response(json_encode($e->getMessage()), 400);
        }
    }
```

try multiple config on facebook, but not really find out how.

Valid OAuth Redirect URIs
​- foobar.com/connect/facebook/check
​- foobar.com/

Whitelist also as added. try via js there's nothing wrong.
Didn't config Authentication / Provider as we need to manage things by ourselves

Please kindly points out on what i'm missing . Thanks

**Comment by weaverryan** [comment]
Hi!

his is an error specific to Facebook :/. It means that Facebook (for some reason) is not happy with the URL that you are asking it to redirect to. It could even be caused if you are using "http" instead of https - https://wp-native-articles.com/blog/news/how-to-fix-facebook-apps-error-cant-load-url-domain-url-isnt-included-apps-domains/

Sorry I can't help more! I believe it's nothing wrong with how you're using the bundle - but with your Facebook app config.

**Comment by chanondb** [comment]
Thank you for @weaverryan , just quick question. 
Is it possible due to ?
 - we are using cloudflare for https (free version), might be because of this when we do fetchUser from plugin , which make facebook see it as http not https? 
 - Facebook App config, ya since it's "Enforce HTTPS" flag is open so may be..?

**Comment by weaverryan** [comment]
I think Facebook shows you this error before it redirects the user back - so before you call fetchUser(). You can tell me if that’s not what you’re seeing, but if I’m right, then it’s not the cloudflare thing you’re talking about
