### ISSUE TITLE
Facebook login got error ERR_TOO_MANY_REDIRECTS after redirect 

### ISSUE THREAD

**Issue by leyriel** [knpuniversity/oauth2-client-bundle#228]

**Comment by weaverryan** [comment]
Hey! It looks like some kind of redirect loop - that could happen for many reasons. I would setting intercept_redirects to true in `web_profiler.yaml` temporarily - https://symfony.com/doc/current/reference/configuration/web_profiler.html#intercept-redirects - that will help you see which page is redirecting to which page. It is probably some sort of security misconfiguration.

Cheers!
