### ISSUE TITLE
Travis not working

### ISSUE THREAD

**Issue by akondas** [knpuniversity/oauth2-client-bundle#231]
Looks like Travis not working correctly for PR. May I suggest @buddy-works?
I'll be happy to create a ready-made configuration. We recently open builds for open-source projects.

**Comment by akondas** [comment]
Link to example pipeline (from my fork): https://app.buddy.works/akondas/oauth2-client-bundle/pipelines/pipeline/243445

![Screenshot from 2020-03-06 10-54-23](https://user-images.githubusercontent.com/8239917/76072789-e03d4180-5f98-11ea-98f7-2a22f1b5d71c.png)

**Comment by weaverryan** [comment]
Hmm, yea - that is strange - the build *did* run on Travis, but didn't update the PR for some reason - I'm not sure why: https://travis-ci.org/knpuniversity/oauth2-client-bundle/jobs/659074599

I'd like to keep Travis - versus having a different toolset for this bundle. I would also be opening to using GH actions, as quite a lot is moving there :).

Thanks for the offer!
