### ISSUE TITLE
Cannot set config options to mitigate Google API change

### ISSUE THREAD

**Issue by Chrisissorry** [knpuniversity/oauth2-client-bundle#236]
Problem is that Google just changed their security policy for OAuth2: https://github.com/googleapis/google-api-php-client/issues/1821

Clients should set `approval_prompt` to `force` or `prompt` to `consent` (or any other allowed values). However, both configuration options are not allowed in this library.

**Comment by hugovk** [comment]
Here's the docs for `prompt`:

https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters

**Comment by Chrisissorry** [comment]
This works:

```
    public function connectAction(): RedirectResponse
    {
        return $this->clientRegistry
            ->getClient('google')
            ->redirect(self::$scopes, ['prompt' => 'consent']);
    }
```

**Comment by weaverryan** [comment]
Hmm, I think we need to wait for an upstream fix - probably in https://github.com/thephpleague/oauth2-google/issues/87 - and I've heard that Google may have fixed this problem anyways.

If someone wants to add the `prompt` option to the config, that would be awesome :).

Cheers!
