### ISSUE TITLE
Accessing methods in Client Library?

### ISSUE THREAD

**Issue by mike240se** [knpuniversity/oauth2-client-bundle#238]
I am using the Azure client library and it seems this bundle doesnt let me access its additional methods for working with Azure like ->get().   ->post(), etc for working with graph, getting user profile info, etc.

Is there a way I can either have the bundle expose those methods or perhaps extend the bundle to add them?

I tried to use the full Azure provider after authenticating the user with this bundle and its working after realizing i need to set the tenant id but I am wondering if its possible to do this in a cleaner fashion using the bundle?

 
```

  /** @var AzureClient $client */
        $client = $clientRegistry->getClient('azure');
        $token = $client->getAccessToken();

        $provider = new Azure(['clientId' => $_ENV['OAUTH_AZURE_CLIENT_ID'],
            'clientSecret' => $_ENV['OAUTH_AZURE_CLIENT_SECRET'],
            'redirectUri' => $this->generateUrl('connect_azure_check', [], UrlGeneratorInterface::ABSOLUTE_URL)
            ]);
  $provider->tenant = "my_tenant_id"

        $me = $provider->get("me", $token);
```

**Comment by weaverryan** [comment]
Hey @mike240se!

I think you can use the `getOAuth2Provider()` method:

```php
/** @var AzureClient $client */
$client = $clientRegistry->getClient('azure');
$token = $client->getAccessToken();

$provider = $client->getOAuth2Provider();
$provider->tenant = "my_tenant_id";

$me = $provider->get("me", $token);
```

Cheers!

**Comment by mike240se** [comment]
> Hey @mike240se!
> 
> I think you can use the `getOAuth2Provider()` method:
> 
> ```
> /** @var AzureClient $client */
> $client = $clientRegistry->getClient('azure');
> $token = $client->getAccessToken();
> 
> $provider = $client->getOAuth2Provider();
> $provider->tenant = "my_tenant_id";
> 
> $me = $provider->get("me", $token);
> ```
> 
> Cheers!

Thanks Ryan!  PS. I love what you have done with Symfony Casts, I did several videos when it was KNPU in the symfony 2 days and just signed up for a monthly account and love all the great content!
