### ISSUE TITLE
Problem with facebook connect : cURL error 7: Failed to connect to graph.facebook.com port 443: Network is unreachable

### ISSUE THREAD

**Issue by jbpham-lorweb** [knpuniversity/oauth2-client-bundle#248]
Hi,

I'm using the bundle with symfony 4.4, php 7.3
I have a problem with the facebook client, I already download league for fb.
Do you know where is the problem ? Thanks 

![image](https://user-images.githubusercontent.com/48094333/85270022-02d86500-b479-11ea-9635-fcd56e10e598.png)

**Comment by weaverryan** [comment]
Hey @jbpham-lorweb!

Hmm, I have no idea - my guess is that there was either a temporary outage, or you have something (not sure what) misconfigured on your system that doesn't allow you to fetch this URL (possibly a company firewall?) or has a problem accessing things over SSL.

Good luck!
