### ISSUE TITLE
Apple Login sends "state" as POST instead of GET

### ISSUE THREAD

**Issue by Dandrum** [knpuniversity/oauth2-client-bundle#249]
We get the Error `Invalid state parameter passed in callback URL.` Because the state isn't a GET value. So far i know they changed it because of security issues or so. Is it possible to change if state check is GET or POST for a provider ?

Best,
Dan

**Comment by weaverryan** [comment]
Hey @Dandrum!

First, in case it helps, here is where the "state" check is performed: https://github.com/knpuniversity/oauth2-client-bundle/blob/2e54646ae5b1a41bde7985ab1dbdd5cb4ceb0462/src/Client/OAuth2Client.php#L93-L99


> We get the Error Invalid state parameter passed in callback URL. Because the state isn't a GET value

I don't know anything about Apple Login, but when they redirect back to your site, I don't think they can do that with anything other than a GET request (but I could be wrong). Anyways, if that is the case (that the state is POST data), you'll probably need to set your client as "stateless"  `use_state: false` and then check the state manually yourself (including setting the state to the session before redirecting to Apple). It's not too much work - so I think that might be the simplest.

I'm not against also looking for state as a POST parameter, but I've never heard of this before with OAuth.

Cheers!

**Comment by Dandrum** [comment]
Hi,
i think it was an security issue so apple changed it to POST instead of GET. 
The apple sign in bundle you ref to in your docs are using POST too -> [https://github.com/patrickbussmann/oauth2-apple#authorization-code-flow ](https://github.com/patrickbussmann/oauth2-apple#authorization-code-flow )

And the solution in apple docs: -> [https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple#3331292](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple#3331292)

Hope that helps you a bit.
Best, Dan

**Comment by weaverryan** [comment]
Thanks for the info @Dandrum!

Indeed, there seems to be a `form_post` OAuth mode that I wasn't familiar with - https://auth0.com/docs/protocols/oauth2 describes it. And so, our state checking should check for state in both `$request->query()` and `$request->request()`. I'd welcome a pull request if you'd like to make that change. Probably we should check `$request->request()` first (i.e. give that one priority).
