### ISSUE TITLE
OAuthException: (#200) Missing Permissions

### ISSUE THREAD

**Issue by odrik** [knpuniversity/oauth2-client-bundle#252]
Hello, I recently have this error "OAuthException: (#200) Missing Permissions" for login with Facebook.

I changed nothing, the code was working before, do you have any idea why I suddenly got this error?

`    public function connectAction(ClientRegistry $clientRegistry)
    {
        return $clientRegistry
            ->getClient('facebook')
            ->redirect([
                'public_profile', 'email' // the scopes you want to access
            ])
            ;
    }
`

<img width="1037" alt="Capture d’écran 2020-07-17 à 15 43 54" src="https://user-images.githubusercontent.com/16124915/87792642-78e7a600-c844-11ea-96f5-c5873b8a430c.png">

**Comment by mhujer** [comment]
@odrik Same here, it stopped working for me as well, so it's not just you.

**Comment by mhujer** [comment]
Just found this https://github.com/thephpleague/oauth2-facebook/pull/54

**Comment by odrik** [comment]
Ok, thanks for your feedback and when I look in the details of my app on https://developers.facebook.com/ I see no permissions missing, I have permission for public_profile and email. I do not understand...

**Comment by odrik** [comment]
> Just found this [thephpleague/oauth2-facebook#54](https://github.com/thephpleague/oauth2-facebook/pull/54)

Yes, I have seen before but I don't deal with "cover{source}".

**Comment by mhujer** [comment]
@odrik If I understand it correctly, the library tries to parse those by default, because they were available when you requested default scope. But they are not anymore. The referenced patch fixes the issues for me.

**Comment by odrik** [comment]
> @odrik If I understand it correctly, the library tries to parse those by default, because they were available when you requested default scope. But they are not anymore. The referenced patch fixes the issues for me.

So, before you had parameters 'public_profile' and 'email' as me in your connectAction function and now ?

**Comment by odrik** [comment]
Ok, I understand I had to edit since /vendor. Thanks.

**Comment by jrushlow** [comment]
@odrik Sorry for the delay! did the fix mentioned above solve the problem for you?

**Comment by jrushlow** [comment]
Im going to close this issue for now, please feel free to reopen if you're still experiencing problems. Thanks!
