### ISSUE TITLE
Unable to use the graph api in TheNetworg/oauth2-azure

### ISSUE THREAD

**Issue by mike240se** [knpuniversity/oauth2-client-bundle#255]
TheNetworg/oauth2-azure has the ability to use it to access the azure graph api.  ive used it with success outside of knp oauth2 bundle, but  when ussing the bundle i get invalidstateexception.  (setting use_state to false throws a different error of No "code" parameter was found (usually this is a query parameter)!)

it appears that with the knp bundle  the authorization code is lost as soon as you authenticate with azure.  i can access the graph api if i do it in my guard authenticator but not outside of it.

thenetworg states: "This library also provides easy interface to make it easier to interact with Azure Graph API and Microsoft Graph, the following methods are available on provider object (**it also handles automatic token refresh flow should it be needed during making the request)**:"

I am guessing the issue is that the automatic token refresh flow doesnt work when using knp bundle is thee issue?

**Comment by mJeromeDiaz** [comment]
same here, but it was a TheNetworg/oauth2-azure problem.
v1.4.2 download by composer is not the last version... download manualy the last version and put in your vendors :D it's very dirty, but works...

**Comment by weaverryan** [comment]
Yea, it looks like they have a bunch of commits to master AFTER v1.4.2 - you might need to ask them for a new release: https://github.com/TheNetworg/oauth2-azure/compare/v1.4.2...master

To get the master version, you could run this:

```
composer require thenetworg/oauth2-azure:@dev
```

Cheers!

**Comment by mike240se** [comment]
FYI TheNetworg released a new release:

https://github.com/TheNetworg/oauth2-azure/issues/122#issuecomment-696893444
