### ISSUE TITLE
What is the usage of $options in ClientRegistry redirect method?

### ISSUE THREAD

**Issue by fd6130** [knpuniversity/oauth2-client-bundle#259]
Hello, what is the usage $options in ClientRegistry redirect method? Do we have docs about that?

**Comment by weaverryan** [comment]
Hi @fd6130!

Fair question :). First, I think you're talking about the `OAuth2Client` class (this is what you get when you call `getClient()` on the registry. The `$options` in redirect are passed to the `getAuthorizationUrl()` of the underlying provider. And those options will differ for each service. For example, if you're using Facebook, then it has (and actually, most/all providers have this option) a <code>scope</code> option you can pass here - https://github.com/thephpleague/oauth2-facebook#authorization-code-flow

I'll update the docs a bit above this method to help :)

**Comment by weaverryan** [comment]
Btw, these basically become the query parameters when redirecting to the OAuth server.
