### ISSUE TITLE
Redirect URL sent on Azure always http

### ISSUE THREAD

**Issue by mikaint** [knpuniversity/oauth2-client-bundle#264]
Even though the app is running on https, the redirect_uri specified on azure URL uses http. I can't find where is this URL created. Please advise. I'm using SF5

**Comment by kdefives** [comment]
Same issue for me.

**Comment by weaverryan** [comment]
Hi!

The redirect_uri is generated right here via the router: https://github.com/knpuniversity/oauth2-client-bundle/blob/master/src/DependencyInjection/ProviderFactory.php#L43

The router is smart enough to generate in https if your site is in https, which makes me wonder if Symfony thinks that you are *not* in HTTPs. This can happen if you're behind a proxy/load balancer (e.g. an aws ELB, or many other systems go through a proxy) and your "trusted proxies" config isn't correct - https://symfony.com/doc/current/deployment/proxies.html

You can check easily to see if this is the situation: grab the Request object in a controller and then `var_dump($request->isSecure())`. If this returns false even though your site is in https, then it is a trusted proxy problem.

Cheers!
