### ISSUE TITLE
Bad link in doc

### ISSUE THREAD

**Issue by Atyz** [knpuniversity/oauth2-client-bundle#27]
Hi :)

https://github.com/knpuniversity/oauth2-client-bundle#1-find--create-your-provider-library
Both links are dead, they does not lead on the right page.

**Comment by bocharsky-bw** [comment]
Hey, @Atyz !

Actually, displayed links are correct, incorrect only their markdown syntax, so you can just copy them from the text and paste it into the browser's address bar. They'll work!
I've fixed it in https://github.com/knpuniversity/oauth2-client-bundle/pull/28 .

Anyway, it's a good catch that must be fixed!
Thank you!

**Comment by weaverryan** [comment]
Fix merged - thanks for the report @Atyz!
