### ISSUE TITLE
state parameter is sent unconditionally

### ISSUE THREAD

**Issue by Bilge** [knpuniversity/oauth2-client-bundle#270]
Even though the client can run in stateless mode, by calling `OAuth2ClientInterface::setAsStateless()`, the `state` parameter is generated and passed regardless of this flag. Although considered mostly harmless, it is nevertheless wasted processor cycles and random entropy.

**Comment by weaverryan** [comment]
Hmm, I agree! But it looks like the PHP League library that we depend on is the one that is *always* sending the `?state=` query parameter - https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L337-L339 - so if I'm right, it would need to be "fixed" there :).

Cheers!

**Comment by Bilge** [comment]
This is 90% true, but the other 10% would still require changes here.

**Comment by weaverryan** [comment]
You might be right about that :). But we don't pass any state information to the method (in the core library) that generates the `?state=` on the authorization URL - that's entirely the core library adding that - https://github.com/knpuniversity/oauth2-client-bundle/blob/8ede9725f8b0d9b6ef5c93f991da8a205d911d5f/src/Client/OAuth2Client.php#L63-L69

Then we only do anything with state if it *is* enabled: https://github.com/knpuniversity/oauth2-client-bundle/blob/8ede9725f8b0d9b6ef5c93f991da8a205d911d5f/src/Client/OAuth2Client.php#L72

But I could be missing something - let me know if I am :).

Cheers!

**Comment by Bilge** [comment]
I just presume whatever mechanism they might add to not pass state would be opt-in for BC reasons, therefore it would imply an update would be needed here also. For that reason I don't think this issue should be closed unless the other library refuses to support the feature.

**Comment by weaverryan** [comment]
Ah! That makes sense :). If they added an option for it, then we might need to update something to support that option.

I *am* going to keep this issue closed, however, because there is no action we can take on this repository right now. Someone would need to do the work on the other repository first so that we could then do something here. It's not ideal to close it, but it helps us not have unactionable issues in the queue.

Cheers!
