### ISSUE TITLE
Realm does not exist

### ISSUE THREAD

**Issue by CV008** [knpuniversity/oauth2-client-bundle#274]
Good morning. Please can I use this bundle for a "bearer only client" in a rest api in symfony ? Or is it only for public client which have UI for redirection ?
I tried to omit the redirection parameters redirect_route and redirect_params: {} because this is not relevant for a bearer only client or rest microservice but it dosnt work.

when i test on postman i have this error message-> Realm does not exist

thx for your help in advance

**Comment by weaverryan** [comment]
Hi!

> Or is it only for public client which have UI for redirection ?

I do not have any real experience with bearer only clients, but if you already have an access token and want to talk to some API using it, you should just use the API client for that API. This bundle is all about *getting* the access token via the authorization code OAuth flow :).

Cheers!
