### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by hktr92** [knpuniversity/oauth2-client-bundle#275]
With PHP 8 around the corner, it would be nice to support this version as well. Even if it's RC, I'm checking the compatibility of this version in my project.

**Comment by weaverryan** [comment]
Definitely agree! The tricky part is that I think we need to switch to GitHub Actions, which supports PHP 8 (from Travis).

**Comment by weaverryan** [comment]
PR's warmly welcome - you could use MakerBundle's GitHub actions setup as inspiration - https://github.com/symfony/maker-bundle/blob/master/.github/workflows/ci.yml

**Comment by derrabus** [comment]
While switching to GitHub Actions is certainly a good idea, it's not a prerequisite for testing with php 8. Travis does provide binaries for php 8 as well.

I've opened a PR: #280
