### ISSUE TITLE
Error 500 Notice: Undefined index: api_version

### ISSUE THREAD

**Issue by VGzsysadm** [knpuniversity/oauth2-client-bundle#278]
Greetings.

I'm using the azure provider.

All works as expected but sometimes, when i turn on the dev mode.

An error 500 is shown

Notice: Undefined index: api_version

vendor\knpuniversity\oauth2-client-bundle\src\DependencyInjection\Providers\AzureProviderConfigurator.php (line 86) 

'pathToken' => $config['path_token'],
            'scope' => $config['scope'],
            'tenant' => $config['tenant'],
            'urlAPI' => $config['url_api'],
            'resource' => $config['resource'],
            'API_VERSION' => $config['api_version'],
            'authWithResource' => $config['auth_with_resource'],
            'defaultEndPointVersion' => $config['default_end_point_version'],
        ];
    }

I did'nt noticed about if this error 500 affects also to the prod mode, didn't confirmed yet, but for the moment no.

The workaround i found is comment the line:

'API_VERSION' => $config['api_version'],

Reload the aplication

uncomment again the line:

'API_VERSION' => $config['api_version'],

As i said, this error appears 1 time of 10.

Symfony versión: 5.1
PHP Versión: 7.4.11

**Comment by weaverryan** [comment]
Hi!

Looks legit! Can you see if #279 would help you (you could just temporarily hack the patch into your code and see if things still work).

Cheers!
