### ISSUE TITLE
how to retrieve token after authentication ?

### ISSUE THREAD

**Issue by floxblah** [knpuniversity/oauth2-client-bundle#281]
Hello,
 sorry if my question is dumb but i'm quiet new with oauth.
i use knpu/oauth2-client-bundle to authenticate the user with keycloack in my symfony app.
I succeeded to implement the authentication with guard and i use the OAuthUserProvider.

Then, i would like to use the token (or refresh token) of my authenticated user and put it in the header of an API call but i don't understand how i can retrieve the token after the authentication?
is there a way to retrieve it after the authentication process or do i have to store it during the authentication process ? 

If i have to store it, which way is the more secure ? in the session ? cookie ? cache ? or somewhere else ?

**Comment by weaverryan** [comment]
Hey @floxblah!

> sorry if my question is dumb but i'm quiet new with oauth.

No worries, OAuth is mysteriously confusing ;). And I'm always happy to answer questions from nice people :).

> is there a way to retrieve it after the authentication process or do i have to store it during the authentication process ?

You need to store it *during* the authentication process. In your authenticator, you fetch the access token and then... if you don't store it, it's gone forever. Make sure you get the access token with this code:

```php
// DO NOT use
// why? This fetches the access token, uses it to get the User, then discards the access token.
// and you can only fetch the access token one time.
$user = $client->fetchUser();

// DO use
$accessToken = $client->getAccessToken();
$user = $client->fetchUserFromToken($accessToken);
```

> If i have to store it, which way is the more secure ? in the session ? cookie ? cache ? or somewhere else ?

Um.... it depends on how you're going to use it. You mentioned:

> i would like to use the token (or refresh token) of my authenticated user and put it in the header of an API call 

So I assume that - after authentication - you want the ability to make more API calls to keycloak. If so, it probably makes sense to store this in the database on the User record. Then, whenever your authenticated user makes a request, you can read that off and make any API calls using their API token that you need. Keep in mind, of course, that API tokens are temporary, and so it will expire eventually. You can (as I think you already know) mitigate that by also storing the refresh token (FYI details here about those https://github.com/knpuniversity/oauth2-client-bundle/issues/260). But even in that case, just be aware that it's possible for that to also fail and eventually you may need to ask the user to log back in via keycloak :).

Cheers!
