### ISSUE TITLE
Steam oauth2

### ISSUE THREAD

**Issue by aecy** [knpuniversity/oauth2-client-bundle#283]
Hi !

Anyone have thinking about Steam login?

Maybe I miss something else ?

It's possible to make my own steam provider by myself? Thanks you

**Comment by weaverryan** [comment]
Hey @aecy!

This bundle integrates with any client packages that have been written to support the PHP League OAuth2 client library - https://github.com/thephpleague/oauth2-client

But, yes, as best I can tell (googling for `php league oauth2 client "steam"`), it doesn't look like there is any OAuth2 client library for that. If you'd like to create one, that would be awesome! After, you could create a pull request here to integrate it. OR, if you just want to get things working for your project, you could create the couple of classes needed to integrate with PHP League (but not actually open source it) then use the generic type - https://github.com/knpuniversity/oauth2-client-bundle#configuring-a-generic-provider

Cheers!

**Comment by aecy** [comment]
Hello @weaverryan !

I found a way, thanks you.
