### ISSUE TITLE
Handling AuthenticationException

### ISSUE THREAD

**Issue by AradEmertat** [knpuniversity/oauth2-client-bundle#294]
Hello there!

I'm using **FOSUserBundle** and User registration is manually by myself
Everything works fine but I just wanna allow **User who already registered in my database** to grant access to Admin 
That's why I check the User in `getUser($credentials, UserProviderInterface $userProvider)` and If exist the User return User else `throw new AuthenticationException();`

But with my codes if User doesn't exist it just shows **Username could not be found** (in white blank page), and I wanted to redirect User to Login Page with this error message.
also, I tried with` return null `instead of User. it's same

```php
public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /** @var GoogleUser $googleUser */
        $googleUser = $this->getGoogleClient()->fetchUserFromToken($credentials);

        $email = $googleUser->getEmail();
        
        $existingUser = $this->em->getRepository(User::class)->findOneBy(['email' => $email]);

        if ($existingUser) {
            return $userProvider->loadUserByUsername($existingUser->getUsername());
        } else {
            throw new AuthenticationException();
        }
}
```
After authentication credentials, in which method should I check the User?
Do I chosen correctly method ?

Thank you for your help

**Comment by weaverryan** [comment]
Hi @AradEmertat!

Your code generally looks fine, though I don't think you need to use the `$userProvider`, as you've already done the work of querying for the user. I'd simplify to:

```php
public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /** @var GoogleUser $googleUser */
        $googleUser = $this->getGoogleClient()->fetchUserFromToken($credentials);

        $email = $googleUser->getEmail();
        
        // this will return a User (authentication success!) or null (authentication failure)
        // no need to throw a custom AuthenticationException. You are free to do that, but
        // if you return null, a sub-class of AuthenticationException is automatically thrown
        // (UsernameNotFoundException)
        return $this->em->getRepository(User::class)->findOneBy(['email' => $email]);
}
```

But this doesn't solve you problem - it's effectively the same thing you have now, just less work :).

You mentioned:

> But with my codes if User doesn't exist it just shows Username could not be found (in white blank page),
> and I wanted to redirect User to Login Page with this error message

When you *fail* to return a User from `getUser()` (i.e. you return null or you throw an AuthenticationException - other than the eventual error you will see, these are identical) then the onAuthenticationFailure() method of your method will be called. Here, you are 100% responsible for determining what the user should see on failure. In your case, you should be redirecting back to the login form. 

My guess is that you're following our docs (good job! But it's not what you want) https://github.com/knpuniversity/oauth2-client-bundle#authenticating-with-guard - and instead, you should be redirecting the user back to the login page, much like a normal "login form authenticator". Here's a good example of what "core" does for login pages (they store the error message in the session, then redirect to the login page https://github.com/symfony/symfony/blob/31545099851b9dfc314561c9e18f95e9f7858121/src/Symfony/Component/Security/Guard/Authenticator/AbstractFormLoginAuthenticator.php#L39-L48)

Good luck!
