### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Mouke** [knpuniversity/oauth2-client-bundle#297]
Hello there,

In your [README.md](https://github.com/knpuniversity/oauth2-client-bundle#1-find--create-your-provider-library) file, in the Generic Provider/Find - Create your Provider Library section, you have a link to learn of to create a provider.

The link is currently broken (https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDER-GUIDE.md instead of, i assume, https://oauth2-client.thephpleague.com/providers/implementing/).

Thank you !

**Comment by bocharsky-bw** [comment]
Good catch!

I agree, the link should point to https://oauth2-client.thephpleague.com/providers/implementing/ instead.

Would you like to create a PR for this?

**Comment by Mouke** [comment]
@bocharsky-bw done.

**Comment by bocharsky-bw** [comment]
Awesome, thanks!
