### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by checkk22** [knpuniversity/oauth2-client-bundle#301]
Hello,
I have a problem when I install the dependency,
checkdir error on a temporary test directory, you will find below a capture

![image](https://user-images.githubusercontent.com/76479659/116057160-cff59380-a67e-11eb-82d5-8684b92d45e1.png)

the result is the same with --prefer-source and earlier versions.

do you have an idea ?

symfony: 4.4.21
php: 7.4.13
composer: 2.0.10

thanks in advance

**Comment by weaverryan** [comment]
Hi @checkk22!

Wow - I have no idea - I've never seen this before! We don't do anything special with how we package this library... so as far as I can tell, this is some weird Composer + your system setup... problem... but I have no idea what. Even a quick googling (for the exact error messages)... I can't find anything. And I can't repeat it locally.

Sorry I can't help more!

**Comment by jrushlow** [comment]
@checkk22 have you tried wiping your `vendor` directory then `composer require knpuniversity/oauth2-client-bundle`? based on the output, that looks like a composer cache issue..

**Comment by Immolare** [comment]
Hey,

Got the same error with latest 2.8.0 version and same config. I tried all solution like composer cacheclear / remove vendor then update, etc. :


Failed to extract knpuniversity/oauth2-client-bundle: (2) '/usr/bin/unzip' -qq '/home/vagrant/project/vendor/composer/tmp-f700d62d83631195f36df9afba92a7b6' -d '/home/vagrant/project/vendor/composer/3df41be1'

checkdir error:  cannot create /home/vagrant/oplanning/vendor/composer/3df41be1/knpuniversity-oauth2-client-bundle-5493de2/tests
File exists
unable to process knpuniversity-oauth2-client-bundle-5493de2/tests/.

etc...

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
Unzip with unzip command failed, falling back to ZipArchive class
Update of knpuniversity/oauth2-client-bundle failed

[ErrorException] ZipArchive::extractTo(): File exists



I have successfully installed the 2.7.0 version, so this might be related to the latest version !

If you need some informations, i'll be glad to help

**Comment by Immolare** [comment]
Hey,

I come back from some investigations about the 2.8.0 fresh install that i've successfully installed :

In my case I had to install the 2.7 from composer and **then** upgrading to 2.8 (via composer update).

Like the error message said, it seems to be related to some cache naming from "tests" folder generation

**Comment by tdierolf** [comment]
Hi. A workmate ran into the same issue, he's running docker on windows. No problems with v2.7 installation, but v2.8 update fails with the unzip error message.

BTW: I'm running docker on Arch Linux and don't have any problems at all.
