### ISSUE TITLE
Cannot extract this bundle on NTFS filesystems from Zip archive

### ISSUE THREAD

**Issue by mormanski** [knpuniversity/oauth2-client-bundle#310]
Version: Tag 2.8.0

Error: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(): File exists

This occurs because there are two directories named "Tests" and "tests" in the root folder. Users installing this bundle on an NTFS file system will get the above error.

**Comment by weaverryan** [comment]
You're correct - that is totally a mistake. That one file in `Tests` should be in `tests`.
