### ISSUE TITLE
AbstractGuardAuthenticator is deprecated

### ISSUE THREAD

**Issue by garak** [knpuniversity/oauth2-client-bundle#316]
>The "KnpU\OAuth2ClientBundle\Security\Authenticator\SocialAuthenticator" class extends "Symfony\Component\Security\Guard\AbstractGuardAuthenticator" that is deprecated since Symfony 5.3, use the new authenticator system instead.

**Comment by DonCallisto** [comment]
I think it's already done https://github.com/knpuniversity/oauth2-client-bundle#using-the-new-symfony-authenticator. It's up to user to implement the right authenticator.
