### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by Matts** [knpuniversity/oauth2-client-bundle#318]
Heyo
Currently the composer.json sticks to "php": ">=7.1.3"
We should see if we can make this ^7.1|^8.0

**Comment by jrushlow** [comment]
Thanks again for the PR - copy of the the comment I left there:

Howdy @Matts, thanks for this addition. Unfortunately it is not needed as the existing version constraint allows any PHP version greater than `7.1.3`.  e.g. PHP 8 || PHP 9, etc.. Checkout https://getcomposer.org/doc/articles/versions.md#version-range

Symfony switched over to using the `>=` version constraint for PHP a while back and we are following suite here as well.

PR #280 implemented PHP 8 support.

Thanks again for your effort, it is greatly appreciated!
