### ISSUE TITLE
Inject ClientRegistry in a service

### ISSUE THREAD

**Issue by orangevinz** [knpuniversity/oauth2-client-bundle#333]
Symfony 5.3

I'm not sure it's related to the bundle but if I use the `ClientRegistry` from a service I have an error I can't figure out.
If I inject in a controller the same way (as a constructor), I don't have any errors...

```php
/** @var \KnpU\OAuth2ClientBundle\Client\Provider\GoogleClient */
private $client;

public function __construct(ClientRegistry $clientRegistry)
{
    $this->client = $clientRegistry->getClient('google');
}
```
` [Symfony\Component\Config\Exception\LoaderLoadException]                                               
  Cannot load resource "kernel::loadRoutes". Make sure there is a loader supporting the "service" type.`

**Comment by weaverryan** [comment]
Hmm, I'm not sure why that would be happening. It's very likely that, when you get this error, there are multiple exceptions on the page. If you look closely, and scroll down (or maybe the other ones are behind a click on Symfony's exception page, I can't remember), the 2nd error will likely have more details about what's going wrong. But, I don't see anything wrong with the code you posted.

**Comment by orangevinz** [comment]
Hi @weaverryan , thanks for your help.
I have this error only when I run a `console c:c` so event with the `-v` mode I struggle to understand.
As a workaround, it works if I just inject the service in the constructor and I init the provider client later as demand, like this.
```php
public function __construct(ClientRegistry $clientRegistry)
{
    $this->clientRegistry = $clientRegistry;
}

private function getClientOauth(): \KnpU\OAuth2ClientBundle\Client\Provider\GoogleClient
{
    return $this->clientRegistry->getClient('google');
}

public function refreshToken($refreshToken)
{
    // ...
    /** @var AccessToken $accessToken */
    $accessToken = $this->getClientOauth()->refreshAccessToken($refreshToken);
   // ...
}
```

**Comment by weaverryan** [comment]
Awesome! I can't explain it (maybe your controller doesn't extend `AbstractController`?), but this is a totally valid work-around.
