### ISSUE TITLE
Twitch client library outdated

### ISSUE THREAD

**Issue by ErdemUyanik** [knpuniversity/oauth2-client-bundle#351]
Hey,

just found this project and wanted to play around with the Twitch API but it seems like the recommended library is way outdated and the maintainer doesnt respond to pull requests/issues anymore.

I tried some forks but could not find one that is actively being maintained. A replace is needed so if anyone knows a working library some help would be appreciated.

**Comment by bocharsky-bw** [comment]
Hey @ErdemUyanik ,

Please, take a look at the new `vertisan/oauth2-twitch-helix` and let me know if that works for you. This is the library that's promoted officially by PHP League, see: https://oauth2-client.thephpleague.com/providers/thirdparty/

**Comment by bocharsky-bw** [comment]
I suppose we can close this issue with #355

**Comment by ErdemUyanik** [comment]
Sorry for the late response, its not that simple to just switch the OAuth2 bundle.
We have to modify the client bundle in order to work with another Twitch bundle.

I will play around with a fork of knpuniversity/oauth2-client-bundle now and see what I can do

**Comment by ErdemUyanik** [comment]
Review #361 please, seems to work for me so far

**Comment by jrushlow** [comment]
Fixed w/ #361
