### ISSUE TITLE
Add a coding style checker and enforce it

### ISSUE THREAD

**Issue by curry684** [knpuniversity/oauth2-client-bundle#36]
Adding a `.php_cs` file would make the project more consistent internally, I noticed a lot of missing comments, long array notation et al.

(I'll be happy to do this if asked but it's commonly considered maintainer's task and privilege to set and enforce standards).

**Comment by weaverryan** [comment]
Hi @curry684!

I would warmly welcome this, and would love if you would add it - I don't often use a cs fixer (and so don't know much about the `.php_cs` files), but it does make a lot of sense for OS projects, and I love the automation of such things. We should probably just base our file off of Symfony's https://github.com/symfony/symfony/blob/master/.php_cs

Cheers!

**Comment by curry684** [comment]
The Symfony one is actually far too specialized and custom given their use of generated code et al, I'll whip up a simple one from one of my other projects.

**Comment by curry684** [comment]
Closed by #37
