### ISSUE TITLE
Dynamic redirect params

### ISSUE THREAD

**Issue by CalvinGrain** [knpuniversity/oauth2-client-bundle#373]
How to set dynamic params?
`
 return $clientRegistry->getClient('keycloak_main')->redirect([],['foo' => 'bar' ]);
`
This does not work. 
When I set it in knpu_oauth2_client.yaml config redirect_params: {foo: 'bar'}
It works, but I need the value to be variable. How to do it?

**Comment by CalvinGrain** [comment]
Found how to do it dirty.
https://github.com/knpuniversity/oauth2-client-bundle/issues/313#issue-902897577

**Comment by hellomedia** [comment]
It worked for me too. 

One thing to keep in mind is that some identity providers (in my case, facebook) are very restrictive with redirect_uri's , which makes it unpractical to send dynamic redirect params.
