### ISSUE TITLE
Attempted to load class "AbstractGuardAuthenticator"

### ISSUE THREAD

**Issue by Ben-Meziani** [knpuniversity/oauth2-client-bundle#380]
I've got this error and I don't know how to fix it :

Attempted to load class "AbstractGuardAuthenticator" from namespace "Symfony\Component\Security\Guard".
Did you forget a "use" statement for another namespace?

It seems like  "AbstractGuardAuthenticator" is deprecated with symfony 6 and I don't know what to use instead of it.

**Comment by weaverryan** [comment]
Hey @Ben-Meziani!

Yes, Guard is gone in Symfony 6. Use the new "authenticator" described in the section right about Guard in the docs - https://github.com/knpuniversity/oauth2-client-bundle#authenticating-with-the-new-symfony-authenticator

Cheers!
