### ISSUE TITLE
AzureProvider - Unrecognized option "graph_api_version"

### ISSUE THREAD

**Issue by CyrilCharlier** [knpuniversity/oauth2-client-bundle#384]
Hi,

I use de Azure Provider and i use this configuration : 
![image](https://user-images.githubusercontent.com/11455745/213182316-e1e6c32c-0e3e-47ca-8adf-870a05693fe5.png)

I use this controller method : 
![image](https://user-images.githubusercontent.com/11455745/213182434-7ddf2787-f07c-40d6-95f7-e3a0d2a830c4.png)

But when i try to go to  "/connect/azure", i have this error : 
![image](https://user-images.githubusercontent.com/11455745/213182588-74a2cc26-fd9e-451a-ac1b-dfefac437c1b.png)

Even if i don't have a graph_api_version in my config.

Any help for that ?

thanks,

**Comment by weaverryan** [comment]
Hey!

Do you see `graph_api_version` in your code anywhere? The error makes it LOOK like, somehow, you DO have a `graph_api_version` option set... even though I don't see it. I can't think of how this error would be happening unless that `graph_api_version` config was being set *somewhere* in your app.

Cheers!

**Comment by CyrilCharlier** [comment]
Hi,

thanks for the reply. After severel hours of research, i decided to take a clean code from cli symfony (webapp project). And it's working perfectly.. 
I will search in my code why i have that now.
Thanks to you,

Cyril
