### ISSUE TITLE
Return Groups in Access Token

### ISSUE THREAD

**Issue by rds3006** [knpuniversity/oauth2-client-bundle#409]
I am trying to get the user details after authenticating with Keycloak v21.0.2. I am getting the details with the user authenticated with the client and client scopes. But I am adding a new client scope of Type Group Membership then the code is breaking and giving me errors as "Notice: Undefined index: error_description" and is not returning anything. 
Group membership Client scope : 
<img width="400" alt="image" src="https://github.com/knpuniversity/oauth2-client-bundle/assets/42768429/264236c9-71fe-48e4-b7d3-bfb5359933a1">
<img width="421" alt="image" src="https://github.com/knpuniversity/oauth2-client-bundle/assets/42768429/2e45b3bc-8966-45bf-b798-6184c1a17130">

Error from Symfony :
<img width="400" alt="image" src="https://github.com/knpuniversity/oauth2-client-bundle/assets/42768429/3ca5bb61-4744-4f1a-91d7-adb9166e84b9">

Now if I remove the group client scope and it is returning back the token. I am not sure if this is issue with Keycloak or the oauth-client-bundle which we are using.

User coming from LDAP/AD Directory will be having group information associated and will have access to application based upon the groups only, hence it is mandatory to get the group in the token.

Any help or suggestion will be appreciated.

**Comment by weaverryan** [comment]
I'm not sure where the problem is either. I'd put a `dd($data, $response)` inside if that `if` statement of `Keycloak.php` right before the line that errors to see WHAT the actual error is that Keycloak is sending back.

I'm going to close, as the error is coming from the Keycloak library itself.
