### ISSUE TITLE
Some PHPUnit tests are failed now on PHP 7 with DEPENDENCIES=dev

### ISSUE THREAD

**Issue by bocharsky-bw** [knpuniversity/oauth2-client-bundle#41]
Probably some third party code was updated/released which cause these errors (we don't have `composer.lock` file here for certain reasons):

https://travis-ci.org/knpuniversity/oauth2-client-bundle/jobs/174438251

**Comment by curry684** [comment]
> Symfony\Component\DependencyInjection\Exception\LogicException: Annotations cannot be enabled as the Doctrine Annotation library is not installed.

That doesn't seem to be third party, more like the bootstrap is no longer installing the annotation loader via Travis.

**Comment by weaverryan** [comment]
Fixed at sha: e87cb729d2ccc37b057181083d054e3370c142ad

I'm not sure what the cause was, but we don't need annotations to be enabled anyways :)

Thanks!
