### ISSUE TITLE
How to get the authenticator to protect all routes if not logged in?

### ISSUE THREAD

**Issue by daniellecareplanner** [knpuniversity/oauth2-client-bundle#417]
Hello, following from the readme, I am setting up a custom authenticator for Google. This is what the supports function looks like:

```
public function supports(Request $request): ?bool
{
    // continue ONLY if the current ROUTE matches the check ROUTE
    return $request->attributes->get('_route') === 'connect_google_check';
}
```

This means we are only using this custom authenticator if the route has come from Google, however I want to protect all of my other routes so that if the user is not logged in, they cannot be reached. I am unsure of how to proceed, if anyone can point me in the right direction I would be most grateful. Thanks.

**Comment by bocharsky-bw** [comment]
Hey! That `supports()` means your custom authenticator will trigger only for those requests, i.e. actually do the Google authentication process only on that specific page. And that's what we want.

But what you need is a bit different, you need to look at Symfony's `access_control `: https://symfony.com/doc/current/security/access_control.html - with that, you can specify what pages can be accessed publicly, and which require authentication.

I hope that helps! I'm closing this issue as it is not related to this repo but a core Symfony security question instead.
