### ISSUE TITLE
Option approval_prompt is default "auto"

### ISSUE THREAD

**Issue by bilelBejaoui85** [knpuniversity/oauth2-client-bundle#43]
Hi,

Google API forces us to pass the "approval_prompt" = "force" option so that we can retrieve the refresh_token.
The problem is in the redirect function of the OAuth2Client class.

I propose to give the possibility to spend more options as follows:
Public function redirect (array $ scopes = [], $ options = []) {
    .....
}
instead of
Public function redirect (array $ scopes = []) {
         $ Options = [];
        ....
}
So we can crush the frozen values like 'response_type' => 'code' and 'approval_prompt' => 'auto' if we want.

Thanks
BBI Fondative

**Comment by bocharsky-bw** [comment]
It makes sense for me 👍

**Comment by weaverryan** [comment]
@bilelBejaoui85 makes sense! How does #44 look?

**Comment by bilelBejaoui85** [comment]
@weaverryan Very beautiful, Thank you for your quick collaboration  ;)

**Comment by weaverryan** [comment]
Merged and 1.5.0 tagged and released! Cheers!
