### ISSUE TITLE
Please update for Symfony > 7.1

### ISSUE THREAD

**Issue by Evgeny1973** [knpuniversity/oauth2-client-bundle#447]
The **"Symfony\Component\HttpKernel\DependencyInjection\Extension"** class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from **"KnpU\OAuth2ClientBundle\DependencyInjection\KnpUOAuth2ClientExtension"**.

**Comment by bocharsky-bw** [comment]
Any volunteers who want to help with this issue?

**Comment by Evgeny1973** [comment]
Can't the authors of the bundle themselves add _\Extension_  to the end of the line _use Symfony\Component\DependencyInjection\Extension_??
