### ISSUE TITLE
OAuth2 client libraries like Facebook needs "league/oauth2-client": "^2.0" to be installed!

### ISSUE THREAD

**Issue by giovkanata** [knpuniversity/oauth2-client-bundle#48]
I would like to switch to this library from HWIOAuthBundle (we like so much Guard 👍), but client libraries like Facebook, Github, Instagram, Google, Linkedin, Bitbucket (and maybe others...) have a required dependency with `"league/oauth2-client": "^2.0"` that's locked at the `"league/oauth2-client": "^1.0"` version in this bundle. How we can resolve the issue?

**Comment by bocharsky-bw** [comment]
I'm wondering will`"league/oauth2-client": "^1.0|^2.0"` be enough for `knpuniversity/oauth2-client-bundle`?

**Comment by weaverryan** [comment]
@bocharsky-bw yep, that's what we need! But, there may have been some BC breaks for version 2. If so, we'll need to write some code so that our library works with both.

OR, if version 2 is just too different, we would need to bump our dependency to oauth2-client version 2 and release a new major version of this bundle.

**Comment by weaverryan** [comment]
Actually, if the CHANGELOG is accurate, very little changed: https://github.com/thephpleague/oauth2-client/blob/master/CHANGELOG.md#200

It might be just enough to make that change to composer.json. @bocharsky-bw do you want to make a PR to try it? We can see if the tests pass!

**Comment by bocharsky-bw** [comment]
@weaverryan Yes, let's if tests pass first. I opened #49

**Comment by weaverryan** [comment]
Done! And new version tagged at 1.9.0.

Thanks for the ping on this! I hadn't noticed the new 2.0 version of the lib

**Comment by giovkanata** [comment]
Thank you so much! So fast!
