### ISSUE TITLE
Can't install in Symfony 2.7.33

### ISSUE THREAD

**Issue by imanalopher** [knpuniversity/oauth2-client-bundle#56]
Using version ^1.10 for knpuniversity/oauth2-client-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for knpuniversity/oauth2-client-bundle ^1.10 -> satisfiable by knpuniversity/oauth2-client-bundle[1.10.0].
    - Conclusion: remove symfony/symfony v2.7.33
    - Conclusion: don't install symfony/symfony v2.7.33
    - knpuniversity/oauth2-client-bundle 1.10.0 requires symfony/dependency-injection ^2.8|^3.0 -> satisfiable by symfony/dependency-injection[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6].
    - don't install symfony/dependency-injection v2.8.0|don't install symfony/symfony v2.7.33
    - don't install symfony/dependency-injection v2.8.1|don't install symfony/symfony v2.7.33
    - don't install symfony/dependency-injection v2.8.10|don't install symfony/symfony v2.7.33
    - don't install symfony/dependency-injection v2.8.11|don't install symfony/symfony v2.7.33
..................................................................................................................................................................

**Comment by imanalopher** [comment]
@weaverryan Can you help here? Any idea?

**Comment by larzuk91** [comment]
You are using Symfony 2.7 right? In that case you would have to upgrade to at least 2.8, or you could find a lower version of this bundle that doesn't break your app

**Comment by imanalopher** [comment]
@larzuk91 Thanks

**Comment by larzuk91** [comment]
you are welcome :)
