### ISSUE TITLE
Facebook Provider - Invalid State Exception 

### ISSUE THREAD

**Issue by luchianenco** [knpuniversity/oauth2-client-bundle#58]
I have Implemented a oauth2 sandbox, but currently I get error when I try to log in with the Facebook Provider. Any hint what is wrong?

`
/app/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php:97: {

    : if (!$actualState || ($actualState !== $expectedState)) {

    :     throw new InvalidStateException('Invalid state');

    : }

  }
`

this is my config.yml:

`
knpu_oauth2_client:

    clients:

        facebook_main:

            type: facebook

            client_id: "%facebook_app_id%"

            client_secret: "%facebook_app_secret%"

            redirect_route: connect_facebook_check

            redirect_params: {}

            graph_api_version: v2.8
`

**Comment by weaverryan** [comment]
Yo @luchianenco!

Hmmm! So, the state key should be automatically set to your session in the `redirect()` method: https://github.com/knpuniversity/oauth2-client-bundle/blob/548d903a09513237515021def1d2f6a23741f883/src/Client/OAuth2Client.php#L72. Are you using this method to redirect?

If you are, when you redirect to Facebook, you should see a `state=XXXXXX` query parameter in the URL. Is it there? Then, when Facebook redirects back to your site, that same `state=XXXXXX` should be on the URL to your site. Is it there?

There are a few places where things could be going wrong: (A) the `state` query parameter is not being sent when redirecting to Facebook, (B) the `state` query parameter is not being sent when Facebook is redirecting back to your site (unlikely, this would be a Facebook bug) or (C) some problem with storing/fetching the state from the session.

Cheers!

**Comment by luchianenco** [comment]
Hi @weaverryan my bad.... didn't notice that in twig the wrong route was used for redirect

**Comment by weaverryan** [comment]
no worries!
