### ISSUE TITLE
We need to add a lot more providers!

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/oauth2-client-bundle#7]
We should support as many providers as possible, and there are _many_: https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDERS.md
- [x] Google #3
- [x] Instagram
- [x] LinkedIn #9
- [ ] VK #10 (was reverted)

... and I would accept any other additions

**Comment by javiereguiluz** [comment]
Wouldn't Google, Facebook, Twitter, LinkedIn, Instagram and GitHub cover 99% of the needs? I'd say those are enough for the first version of the bundle.

**Comment by Babacooll** [comment]
I can manage the Twitch provider if nobody has planed to do it.

**Comment by fatihkahveci** [comment]
If we can add Yahoo and Yandex provider too it will be cool for first release.

**Comment by weaverryan** [comment]
@javiereguiluz I agree, I won't wait for providers to make a release. I'm not afraid of making many more releases after as we add more providers.

@Babacooll I've never used Twitch, but that would be rad!

**Comment by kbond** [comment]
How could Twitter be added? It is my understanding it is [oauth1](https://github.com/thephpleague/oauth1-client).

**Comment by weaverryan** [comment]
Ah yea, we can't support Twitter. I'm not opposed to supporting OAuth1 - obviously Twitter makes a good case for it, but I don't know if it's the *only* one. I also don't know if it'll be a huge pain to try to integrate it in cleanly (i.e. hacky), or if it could be done cleanly. There *is* an OAuth1 library from the PHP league... and perhaps we should *not* support it, but mention something in the README (e.g. use this OAuth1 library directly if you need something like Twitter). Afterall, this bundle is mostly a think integration layer.

**Comment by jmolivas** [comment]
@kbond @weaverryan I found a project for Twitter https://github.com/Maslosoft/oauth2-twitter but is not working properly.

**Comment by pmaselkowski** [comment]
Hello, 
Maslosoft/oauth2-twitter project is on hold until twitter fully implements oauth2.

**Comment by weaverryan** [comment]
fwiw - here's a quick answer for others that find this on how you could use the phpleage oauth1 library in Symfony to connect with Twitter: http://knpuniversity.com/blog/KnpUOAuth2ClientBundle#comment-3086507464

**Comment by proArtex** [comment]
Vote for twitter provider

**Comment by jokoast** [comment]
Isn't Twitter using Oauth2 ? Why isn't it implemented ?

**Comment by weaverryan** [comment]
Hi! 

Because there is not a provider for twitter - https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md - because I believe that Twitter's OAuth2 support is, in fact, very limited - e.g. https://github.com/Maslosoft/oauth2-twitter#oauth2-twitter

Cheers!
