### ISSUE TITLE
OAuthException: (#12) bio field is deprecated for versions v2.8 and higher

### ISSUE THREAD

**Issue by gabrielrincon** [knpuniversity/oauth2-client-bundle#89]
Hi everyone.

I have the next error when I try to login with facebook.

> [2018-02-18 12:36:58] request.CRITICAL: Uncaught PHP Exception League\OAuth2\Client\Provider\Exception\IdentityProviderException: "OAuthException: (#12) bio field is deprecated for versions v2.8 and higher" at /home/danielshobot/public_html/vendor/league/oauth2-facebook/src/Provider/Facebook.php line 156 {"exception":"[object] (League\\OAuth2\\Client\\Provider\\Exception\\IdentityProviderException(code: 12): OAuthException: (#12) bio field is deprecated for versions v2.8 and higher at /home/shobot/public_html/vendor/league/oauth2-facebook/src/Provider/Facebook.php:156)"} []

**Comment by gabrielrincon** [comment]
The error is on Facebook.php in the line 110.

``public function getResourceOwnerDetailsUrl(AccessToken $token)
    {
        $fields = [
            'id', 'name', 'first_name', 'last_name',
            'email', 'hometown', 'picture.type(large){url,is_silhouette}',
            'cover{source}', 'gender', 'locale', 'link', 'timezone', 'age_range'
        ];

        // backwards compatibility less than 2.8
        if (version_compare(substr($this->graphApiVersion, 1), '2.8') < 0) {
            $fields[] = 'bio';
        }

        $appSecretProof = AppSecretProof::create($this->clientSecret, $token->getToken());

        return $this->getBaseGraphUrl().$this->graphApiVersion.'/me?fields='.implode(',', $fields)
                        .'&access_token='.$token.'&appsecret_proof='.$appSecretProof;
    }

I removed:

`// backwards compatibility less than 2.8
        if (version_compare(substr($this->graphApiVersion, 1), '2.8') < 0) {
            $fields[] = 'bio';
        }`


But I lost backwards compatibility. How can I to fox this line?

Thanks

**Comment by Soullivaneuh** [comment]
This error is not related to the bundle but the facebook oauth library.

BTW, there are already some issues telling about that: https://github.com/thephpleague/oauth2-facebook/issues?q=is%3Aissue+bio+is%3Aclosed

**Comment by MyKrzysiu** [comment]
Just change:

```
knpu_oauth2_client:
    clients:
        facebook_main:
            graph_api_version: v2.8
```

graph_api_version with 2.3 to 28, if you have copied config from documentation.

**Comment by weaverryan** [comment]
See #91. You're correct that the docs were showing an out-dated version. So, let's fix that :)
