### ISSUE TITLE
Generic provider throws LogicException for missing package

### ISSUE THREAD

**Issue by GriefCode** [knpuniversity/oauth2-client-bundle#93]
When using a generic provider there is no further `composer require` needed. However, the Extension still asks to require an empty package.

https://github.com/knpuniversity/oauth2-client-bundle/blob/master/src/DependencyInjection/KnpUOAuth2ClientExtension.php#L224-L230

```
# bin/console cache:clear
In KnpUOAuth2ClientExtension.php line 225:
  Run `composer require ` in order to use the "generic" OAuth provider.
```

Please fix...

**Comment by bocharsky-bw** [comment]
Thanks for this report!

I see it checks for provider class before throwing exception: `if ($this->checkExternalClassExistence && !class_exists($providerClass))`, so if your provider's class exists - you should not see this error. What is your provider class?

**Comment by GriefCode** [comment]
I'm using a custom provider as I use a generic oauth2 server, this is my provider class:
`<?php

namespace App\Security\Provider;

use League\OAuth2\Client\Provider\AbstractProvider;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use League\OAuth2\Client\Provider\ResourceOwnerInterface;
use League\OAuth2\Client\Token\AccessToken;
use Psr\Http\Message\ResponseInterface;

class IPSProvider extends AbstractProvider {
    /**
     * Returns the base URL for authorizing a client.
     *
     * Eg. https://oauth.service.com/authorize
     *
     * @return string
     */
    public function getBaseAuthorizationUrl() {
        return "https:/whatever.com/oauth/authorize.php";
    }

    /**
     * Returns the base URL for requesting an access token.
     *
     * Eg. https://oauth.service.com/token
     *
     * @param array $params
     * @return string
     */
    public function getBaseAccessTokenUrl(array $params) {
        return "https://whatever.com/oauth/token.php";
    }

    /**
     * Returns the URL for requesting the resource owner's details.
     *
     * @param AccessToken $token
     * @return string
     */
    public function getResourceOwnerDetailsUrl(AccessToken $token) {
        return "https://whatever.com/oauth/me.php";
    }

    /**
     * Returns the default scopes used by this provider.
     *
     * This should only be the scopes that are required to request the details
     * of the resource owner, rather than all the available scopes.
     *
     * @return array
     */
    protected function getDefaultScopes() {
        return [];
    }

    /**
     * Checks a provider response for errors.
     *
     * @throws IdentityProviderException
     * @param  ResponseInterface $response
     * @param  array|string $data Parsed response data
     * @return void
     */
    protected function checkResponse(ResponseInterface $response, $data) {
    }

    /**
     * Generates a resource owner object from a successful resource owner
     * details request.
     *
     * @param  array $response
     * @param  AccessToken $token
     * @return ResourceOwnerInterface
     */
    protected function createResourceOwner(array $response, AccessToken $token) {
    }
}
`
And this is my config:
`
knpu_oauth2_client:
    clients:
        # will create service: "knpu.oauth2.client.foo_bar_oauth"
        # an instance of: KnpU\OAuth2ClientBundle\Client\OAuth2Client
        ips:
            type: generic
            provider_class: App\Security\Provider\IPSProvider

            # optional: a class that extends OAuth2Client
            # client_class: Some\Custom\Client

            # optional: if your provider has custom constructor options
            # provider_options: {}

            # now, all the normal options!
            client_id: <client_id>
            client_secret: <client_secret>
            redirect_route: oauth2_connect_ips_check
            redirect_params: {}
`
Could it be possible caused by using symfony 4.1?

**Comment by bocharsky-bw** [comment]
Thanks for providing this info! I don't think the problem with Symfony 4.1. As for me, it looks like Composer autoloader can't find this class. According to your config, your class should have exactly the next path: `src/Security/Provider/IPSProvider.php` and in `composer.json` you should have this `App\` alias as:
```json
{
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
}
```

Please, could you double check that this is true for you?

**Comment by GriefCode** [comment]
I can confirm that the autoloader setting is correct, according to the composer.json:
```
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
```
Maybe, I haven't dumped the composer file, but that should have been done automatically after using the composer install. I will check that later today when I am back home, as well as provide the info about the dump.

**Comment by GriefCode** [comment]
Sorry for the late reply, was a bit busy.
It appears that it was not dumped. It is working now as expected. Thanks for your help 😃

**Comment by bocharsky-bw** [comment]
Yay, glad it wasn't a bug on our side :)

Cheers!
